// Code generated by ent, DO NOT EDIT.

package subscriptionresetcard

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/AsukaCC/EasySub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldSubscriptionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldGroupID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldStatus, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldIssuedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldConsumedAt, v))
}

// IssuedBy applies equality check predicate on the "issued_by" field. It's identical to IssuedByEQ.
func IssuedBy(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldIssuedBy, v))
}

// ConsumedBy applies equality check predicate on the "consumed_by" field. It's identical to ConsumedByEQ.
func ConsumedBy(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldConsumedBy, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldSourceID, v))
}

// GrantBatchID applies equality check predicate on the "grant_batch_id" field. It's identical to GrantBatchIDEQ.
func GrantBatchID(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldGrantBatchID, v))
}

// GrantIndex applies equality check predicate on the "grant_index" field. It's identical to GrantIndexEQ.
func GrantIndex(v int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldGrantIndex, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldUpdatedAt, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldSubscriptionID, v))
}

// SubscriptionIDContains applies the Contains predicate on the "subscription_id" field.
func SubscriptionIDContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldSubscriptionID, v))
}

// SubscriptionIDHasPrefix applies the HasPrefix predicate on the "subscription_id" field.
func SubscriptionIDHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldSubscriptionID, v))
}

// SubscriptionIDHasSuffix applies the HasSuffix predicate on the "subscription_id" field.
func SubscriptionIDHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldSubscriptionID, v))
}

// SubscriptionIDEqualFold applies the EqualFold predicate on the "subscription_id" field.
func SubscriptionIDEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldSubscriptionID, v))
}

// SubscriptionIDContainsFold applies the ContainsFold predicate on the "subscription_id" field.
func SubscriptionIDContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldSubscriptionID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldGroupID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldStatus, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldIssuedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotNull(FieldConsumedAt))
}

// IssuedByEQ applies the EQ predicate on the "issued_by" field.
func IssuedByEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedByNEQ applies the NEQ predicate on the "issued_by" field.
func IssuedByNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldIssuedBy, v))
}

// IssuedByIn applies the In predicate on the "issued_by" field.
func IssuedByIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldIssuedBy, vs...))
}

// IssuedByNotIn applies the NotIn predicate on the "issued_by" field.
func IssuedByNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldIssuedBy, vs...))
}

// IssuedByGT applies the GT predicate on the "issued_by" field.
func IssuedByGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldIssuedBy, v))
}

// IssuedByGTE applies the GTE predicate on the "issued_by" field.
func IssuedByGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldIssuedBy, v))
}

// IssuedByLT applies the LT predicate on the "issued_by" field.
func IssuedByLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldIssuedBy, v))
}

// IssuedByLTE applies the LTE predicate on the "issued_by" field.
func IssuedByLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldIssuedBy, v))
}

// IssuedByContains applies the Contains predicate on the "issued_by" field.
func IssuedByContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldIssuedBy, v))
}

// IssuedByHasPrefix applies the HasPrefix predicate on the "issued_by" field.
func IssuedByHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldIssuedBy, v))
}

// IssuedByHasSuffix applies the HasSuffix predicate on the "issued_by" field.
func IssuedByHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldIssuedBy, v))
}

// IssuedByIsNil applies the IsNil predicate on the "issued_by" field.
func IssuedByIsNil() predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIsNull(FieldIssuedBy))
}

// IssuedByNotNil applies the NotNil predicate on the "issued_by" field.
func IssuedByNotNil() predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotNull(FieldIssuedBy))
}

// IssuedByEqualFold applies the EqualFold predicate on the "issued_by" field.
func IssuedByEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldIssuedBy, v))
}

// IssuedByContainsFold applies the ContainsFold predicate on the "issued_by" field.
func IssuedByContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldIssuedBy, v))
}

// ConsumedByEQ applies the EQ predicate on the "consumed_by" field.
func ConsumedByEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldConsumedBy, v))
}

// ConsumedByNEQ applies the NEQ predicate on the "consumed_by" field.
func ConsumedByNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldConsumedBy, v))
}

// ConsumedByIn applies the In predicate on the "consumed_by" field.
func ConsumedByIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldConsumedBy, vs...))
}

// ConsumedByNotIn applies the NotIn predicate on the "consumed_by" field.
func ConsumedByNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldConsumedBy, vs...))
}

// ConsumedByGT applies the GT predicate on the "consumed_by" field.
func ConsumedByGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldConsumedBy, v))
}

// ConsumedByGTE applies the GTE predicate on the "consumed_by" field.
func ConsumedByGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldConsumedBy, v))
}

// ConsumedByLT applies the LT predicate on the "consumed_by" field.
func ConsumedByLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldConsumedBy, v))
}

// ConsumedByLTE applies the LTE predicate on the "consumed_by" field.
func ConsumedByLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldConsumedBy, v))
}

// ConsumedByContains applies the Contains predicate on the "consumed_by" field.
func ConsumedByContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldConsumedBy, v))
}

// ConsumedByHasPrefix applies the HasPrefix predicate on the "consumed_by" field.
func ConsumedByHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldConsumedBy, v))
}

// ConsumedByHasSuffix applies the HasSuffix predicate on the "consumed_by" field.
func ConsumedByHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldConsumedBy, v))
}

// ConsumedByIsNil applies the IsNil predicate on the "consumed_by" field.
func ConsumedByIsNil() predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIsNull(FieldConsumedBy))
}

// ConsumedByNotNil applies the NotNil predicate on the "consumed_by" field.
func ConsumedByNotNil() predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotNull(FieldConsumedBy))
}

// ConsumedByEqualFold applies the EqualFold predicate on the "consumed_by" field.
func ConsumedByEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldConsumedBy, v))
}

// ConsumedByContainsFold applies the ContainsFold predicate on the "consumed_by" field.
func ConsumedByContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldConsumedBy, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldSourceID, v))
}

// GrantBatchIDEQ applies the EQ predicate on the "grant_batch_id" field.
func GrantBatchIDEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldGrantBatchID, v))
}

// GrantBatchIDNEQ applies the NEQ predicate on the "grant_batch_id" field.
func GrantBatchIDNEQ(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldGrantBatchID, v))
}

// GrantBatchIDIn applies the In predicate on the "grant_batch_id" field.
func GrantBatchIDIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldGrantBatchID, vs...))
}

// GrantBatchIDNotIn applies the NotIn predicate on the "grant_batch_id" field.
func GrantBatchIDNotIn(vs ...string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldGrantBatchID, vs...))
}

// GrantBatchIDGT applies the GT predicate on the "grant_batch_id" field.
func GrantBatchIDGT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldGrantBatchID, v))
}

// GrantBatchIDGTE applies the GTE predicate on the "grant_batch_id" field.
func GrantBatchIDGTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldGrantBatchID, v))
}

// GrantBatchIDLT applies the LT predicate on the "grant_batch_id" field.
func GrantBatchIDLT(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldGrantBatchID, v))
}

// GrantBatchIDLTE applies the LTE predicate on the "grant_batch_id" field.
func GrantBatchIDLTE(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldGrantBatchID, v))
}

// GrantBatchIDContains applies the Contains predicate on the "grant_batch_id" field.
func GrantBatchIDContains(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContains(FieldGrantBatchID, v))
}

// GrantBatchIDHasPrefix applies the HasPrefix predicate on the "grant_batch_id" field.
func GrantBatchIDHasPrefix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasPrefix(FieldGrantBatchID, v))
}

// GrantBatchIDHasSuffix applies the HasSuffix predicate on the "grant_batch_id" field.
func GrantBatchIDHasSuffix(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldHasSuffix(FieldGrantBatchID, v))
}

// GrantBatchIDEqualFold applies the EqualFold predicate on the "grant_batch_id" field.
func GrantBatchIDEqualFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEqualFold(FieldGrantBatchID, v))
}

// GrantBatchIDContainsFold applies the ContainsFold predicate on the "grant_batch_id" field.
func GrantBatchIDContainsFold(v string) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldContainsFold(FieldGrantBatchID, v))
}

// GrantIndexEQ applies the EQ predicate on the "grant_index" field.
func GrantIndexEQ(v int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldEQ(FieldGrantIndex, v))
}

// GrantIndexNEQ applies the NEQ predicate on the "grant_index" field.
func GrantIndexNEQ(v int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNEQ(FieldGrantIndex, v))
}

// GrantIndexIn applies the In predicate on the "grant_index" field.
func GrantIndexIn(vs ...int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldIn(FieldGrantIndex, vs...))
}

// GrantIndexNotIn applies the NotIn predicate on the "grant_index" field.
func GrantIndexNotIn(vs ...int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldNotIn(FieldGrantIndex, vs...))
}

// GrantIndexGT applies the GT predicate on the "grant_index" field.
func GrantIndexGT(v int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGT(FieldGrantIndex, v))
}

// GrantIndexGTE applies the GTE predicate on the "grant_index" field.
func GrantIndexGTE(v int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldGTE(FieldGrantIndex, v))
}

// GrantIndexLT applies the LT predicate on the "grant_index" field.
func GrantIndexLT(v int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLT(FieldGrantIndex, v))
}

// GrantIndexLTE applies the LTE predicate on the "grant_index" field.
func GrantIndexLTE(v int) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.FieldLTE(FieldGrantIndex, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionResetCard) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionResetCard) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionResetCard) predicate.SubscriptionResetCard {
	return predicate.SubscriptionResetCard(sql.NotPredicates(p))
}
