// Code generated by ent, DO NOT EDIT.

package supportticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the supportticket type in the database.
	Label = "support_ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOrigin holds the string denoting the origin field in the database.
	FieldOrigin = "origin"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAPIKeyNameSnapshot holds the string denoting the api_key_name_snapshot field in the database.
	FieldAPIKeyNameSnapshot = "api_key_name_snapshot"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldGroupNameSnapshot holds the string denoting the group_name_snapshot field in the database.
	FieldGroupNameSnapshot = "group_name_snapshot"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldRefundID holds the string denoting the refund_id field in the database.
	FieldRefundID = "refund_id"
	// FieldRefundDecision holds the string denoting the refund_decision field in the database.
	FieldRefundDecision = "refund_decision"
	// FieldApprovedPrincipalAmount holds the string denoting the approved_principal_amount field in the database.
	FieldApprovedPrincipalAmount = "approved_principal_amount"
	// FieldReviewerID holds the string denoting the reviewer_id field in the database.
	FieldReviewerID = "reviewer_id"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewed_at"
	// FieldReopenCount holds the string denoting the reopen_count field in the database.
	FieldReopenCount = "reopen_count"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldLastUserActivityAt holds the string denoting the last_user_activity_at field in the database.
	FieldLastUserActivityAt = "last_user_activity_at"
	// FieldLastAdminActivityAt holds the string denoting the last_admin_activity_at field in the database.
	FieldLastAdminActivityAt = "last_admin_activity_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the supportticket in the database.
	Table = "support_tickets"
)

// Columns holds all SQL columns for supportticket fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldCategory,
	FieldStatus,
	FieldOrigin,
	FieldTitle,
	FieldAPIKeyID,
	FieldAPIKeyNameSnapshot,
	FieldGroupID,
	FieldGroupNameSnapshot,
	FieldOrderID,
	FieldRefundID,
	FieldRefundDecision,
	FieldApprovedPrincipalAmount,
	FieldReviewerID,
	FieldReviewedAt,
	FieldReopenCount,
	FieldResolvedAt,
	FieldClosedAt,
	FieldLastUserActivityAt,
	FieldLastAdminActivityAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultOrigin holds the default value on creation for the "origin" field.
	DefaultOrigin string
	// OriginValidator is a validator for the "origin" field. It is called by the builders before save.
	OriginValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultAPIKeyNameSnapshot holds the default value on creation for the "api_key_name_snapshot" field.
	DefaultAPIKeyNameSnapshot string
	// APIKeyNameSnapshotValidator is a validator for the "api_key_name_snapshot" field. It is called by the builders before save.
	APIKeyNameSnapshotValidator func(string) error
	// DefaultGroupNameSnapshot holds the default value on creation for the "group_name_snapshot" field.
	DefaultGroupNameSnapshot string
	// GroupNameSnapshotValidator is a validator for the "group_name_snapshot" field. It is called by the builders before save.
	GroupNameSnapshotValidator func(string) error
	// DefaultRefundDecision holds the default value on creation for the "refund_decision" field.
	DefaultRefundDecision string
	// RefundDecisionValidator is a validator for the "refund_decision" field. It is called by the builders before save.
	RefundDecisionValidator func(string) error
	// DefaultReopenCount holds the default value on creation for the "reopen_count" field.
	DefaultReopenCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the SupportTicket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOrigin orders the results by the origin field.
func ByOrigin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrigin, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAPIKeyNameSnapshot orders the results by the api_key_name_snapshot field.
func ByAPIKeyNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyNameSnapshot, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByGroupNameSnapshot orders the results by the group_name_snapshot field.
func ByGroupNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupNameSnapshot, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByRefundID orders the results by the refund_id field.
func ByRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundID, opts...).ToFunc()
}

// ByRefundDecision orders the results by the refund_decision field.
func ByRefundDecision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundDecision, opts...).ToFunc()
}

// ByApprovedPrincipalAmount orders the results by the approved_principal_amount field.
func ByApprovedPrincipalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedPrincipalAmount, opts...).ToFunc()
}

// ByReviewerID orders the results by the reviewer_id field.
func ByReviewerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewerID, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByReopenCount orders the results by the reopen_count field.
func ByReopenCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReopenCount, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByLastUserActivityAt orders the results by the last_user_activity_at field.
func ByLastUserActivityAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUserActivityAt, opts...).ToFunc()
}

// ByLastAdminActivityAt orders the results by the last_admin_activity_at field.
func ByLastAdminActivityAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastAdminActivityAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
