// Code generated by ent, DO NOT EDIT.

package supportticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/AsukaCC/EasySub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUserID, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldCategory, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldStatus, v))
}

// Origin applies equality check predicate on the "origin" field. It's identical to OriginEQ.
func Origin(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldOrigin, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldTitle, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyNameSnapshot applies equality check predicate on the "api_key_name_snapshot" field. It's identical to APIKeyNameSnapshotEQ.
func APIKeyNameSnapshot(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldAPIKeyNameSnapshot, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldGroupID, v))
}

// GroupNameSnapshot applies equality check predicate on the "group_name_snapshot" field. It's identical to GroupNameSnapshotEQ.
func GroupNameSnapshot(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldGroupNameSnapshot, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldOrderID, v))
}

// RefundID applies equality check predicate on the "refund_id" field. It's identical to RefundIDEQ.
func RefundID(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldRefundID, v))
}

// RefundDecision applies equality check predicate on the "refund_decision" field. It's identical to RefundDecisionEQ.
func RefundDecision(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldRefundDecision, v))
}

// ApprovedPrincipalAmount applies equality check predicate on the "approved_principal_amount" field. It's identical to ApprovedPrincipalAmountEQ.
func ApprovedPrincipalAmount(v float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldApprovedPrincipalAmount, v))
}

// ReviewerID applies equality check predicate on the "reviewer_id" field. It's identical to ReviewerIDEQ.
func ReviewerID(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldReviewerID, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldReviewedAt, v))
}

// ReopenCount applies equality check predicate on the "reopen_count" field. It's identical to ReopenCountEQ.
func ReopenCount(v int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldReopenCount, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldResolvedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldClosedAt, v))
}

// LastUserActivityAt applies equality check predicate on the "last_user_activity_at" field. It's identical to LastUserActivityAtEQ.
func LastUserActivityAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastUserActivityAt, v))
}

// LastAdminActivityAt applies equality check predicate on the "last_admin_activity_at" field. It's identical to LastAdminActivityAtEQ.
func LastAdminActivityAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastAdminActivityAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldUserID, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldCategory, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldStatus, v))
}

// OriginEQ applies the EQ predicate on the "origin" field.
func OriginEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldOrigin, v))
}

// OriginNEQ applies the NEQ predicate on the "origin" field.
func OriginNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldOrigin, v))
}

// OriginIn applies the In predicate on the "origin" field.
func OriginIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldOrigin, vs...))
}

// OriginNotIn applies the NotIn predicate on the "origin" field.
func OriginNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldOrigin, vs...))
}

// OriginGT applies the GT predicate on the "origin" field.
func OriginGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldOrigin, v))
}

// OriginGTE applies the GTE predicate on the "origin" field.
func OriginGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldOrigin, v))
}

// OriginLT applies the LT predicate on the "origin" field.
func OriginLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldOrigin, v))
}

// OriginLTE applies the LTE predicate on the "origin" field.
func OriginLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldOrigin, v))
}

// OriginContains applies the Contains predicate on the "origin" field.
func OriginContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldOrigin, v))
}

// OriginHasPrefix applies the HasPrefix predicate on the "origin" field.
func OriginHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldOrigin, v))
}

// OriginHasSuffix applies the HasSuffix predicate on the "origin" field.
func OriginHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldOrigin, v))
}

// OriginEqualFold applies the EqualFold predicate on the "origin" field.
func OriginEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldOrigin, v))
}

// OriginContainsFold applies the ContainsFold predicate on the "origin" field.
func OriginContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldOrigin, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldTitle, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDContains applies the Contains predicate on the "api_key_id" field.
func APIKeyIDContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldAPIKeyID, v))
}

// APIKeyIDHasPrefix applies the HasPrefix predicate on the "api_key_id" field.
func APIKeyIDHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldAPIKeyID, v))
}

// APIKeyIDHasSuffix applies the HasSuffix predicate on the "api_key_id" field.
func APIKeyIDHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldAPIKeyID))
}

// APIKeyIDEqualFold applies the EqualFold predicate on the "api_key_id" field.
func APIKeyIDEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldAPIKeyID, v))
}

// APIKeyIDContainsFold applies the ContainsFold predicate on the "api_key_id" field.
func APIKeyIDContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldAPIKeyID, v))
}

// APIKeyNameSnapshotEQ applies the EQ predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotNEQ applies the NEQ predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotIn applies the In predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldAPIKeyNameSnapshot, vs...))
}

// APIKeyNameSnapshotNotIn applies the NotIn predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldAPIKeyNameSnapshot, vs...))
}

// APIKeyNameSnapshotGT applies the GT predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotGTE applies the GTE predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotLT applies the LT predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotLTE applies the LTE predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotContains applies the Contains predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotHasPrefix applies the HasPrefix predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotHasSuffix applies the HasSuffix predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotEqualFold applies the EqualFold predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldAPIKeyNameSnapshot, v))
}

// APIKeyNameSnapshotContainsFold applies the ContainsFold predicate on the "api_key_name_snapshot" field.
func APIKeyNameSnapshotContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldAPIKeyNameSnapshot, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldGroupID))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldGroupID, v))
}

// GroupNameSnapshotEQ applies the EQ predicate on the "group_name_snapshot" field.
func GroupNameSnapshotEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotNEQ applies the NEQ predicate on the "group_name_snapshot" field.
func GroupNameSnapshotNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotIn applies the In predicate on the "group_name_snapshot" field.
func GroupNameSnapshotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldGroupNameSnapshot, vs...))
}

// GroupNameSnapshotNotIn applies the NotIn predicate on the "group_name_snapshot" field.
func GroupNameSnapshotNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldGroupNameSnapshot, vs...))
}

// GroupNameSnapshotGT applies the GT predicate on the "group_name_snapshot" field.
func GroupNameSnapshotGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotGTE applies the GTE predicate on the "group_name_snapshot" field.
func GroupNameSnapshotGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotLT applies the LT predicate on the "group_name_snapshot" field.
func GroupNameSnapshotLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotLTE applies the LTE predicate on the "group_name_snapshot" field.
func GroupNameSnapshotLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotContains applies the Contains predicate on the "group_name_snapshot" field.
func GroupNameSnapshotContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotHasPrefix applies the HasPrefix predicate on the "group_name_snapshot" field.
func GroupNameSnapshotHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotHasSuffix applies the HasSuffix predicate on the "group_name_snapshot" field.
func GroupNameSnapshotHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotEqualFold applies the EqualFold predicate on the "group_name_snapshot" field.
func GroupNameSnapshotEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldGroupNameSnapshot, v))
}

// GroupNameSnapshotContainsFold applies the ContainsFold predicate on the "group_name_snapshot" field.
func GroupNameSnapshotContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldGroupNameSnapshot, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldOrderID))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldOrderID, v))
}

// RefundIDEQ applies the EQ predicate on the "refund_id" field.
func RefundIDEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldRefundID, v))
}

// RefundIDNEQ applies the NEQ predicate on the "refund_id" field.
func RefundIDNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldRefundID, v))
}

// RefundIDIn applies the In predicate on the "refund_id" field.
func RefundIDIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldRefundID, vs...))
}

// RefundIDNotIn applies the NotIn predicate on the "refund_id" field.
func RefundIDNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldRefundID, vs...))
}

// RefundIDGT applies the GT predicate on the "refund_id" field.
func RefundIDGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldRefundID, v))
}

// RefundIDGTE applies the GTE predicate on the "refund_id" field.
func RefundIDGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldRefundID, v))
}

// RefundIDLT applies the LT predicate on the "refund_id" field.
func RefundIDLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldRefundID, v))
}

// RefundIDLTE applies the LTE predicate on the "refund_id" field.
func RefundIDLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldRefundID, v))
}

// RefundIDContains applies the Contains predicate on the "refund_id" field.
func RefundIDContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldRefundID, v))
}

// RefundIDHasPrefix applies the HasPrefix predicate on the "refund_id" field.
func RefundIDHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldRefundID, v))
}

// RefundIDHasSuffix applies the HasSuffix predicate on the "refund_id" field.
func RefundIDHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldRefundID, v))
}

// RefundIDIsNil applies the IsNil predicate on the "refund_id" field.
func RefundIDIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldRefundID))
}

// RefundIDNotNil applies the NotNil predicate on the "refund_id" field.
func RefundIDNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldRefundID))
}

// RefundIDEqualFold applies the EqualFold predicate on the "refund_id" field.
func RefundIDEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldRefundID, v))
}

// RefundIDContainsFold applies the ContainsFold predicate on the "refund_id" field.
func RefundIDContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldRefundID, v))
}

// RefundDecisionEQ applies the EQ predicate on the "refund_decision" field.
func RefundDecisionEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldRefundDecision, v))
}

// RefundDecisionNEQ applies the NEQ predicate on the "refund_decision" field.
func RefundDecisionNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldRefundDecision, v))
}

// RefundDecisionIn applies the In predicate on the "refund_decision" field.
func RefundDecisionIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldRefundDecision, vs...))
}

// RefundDecisionNotIn applies the NotIn predicate on the "refund_decision" field.
func RefundDecisionNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldRefundDecision, vs...))
}

// RefundDecisionGT applies the GT predicate on the "refund_decision" field.
func RefundDecisionGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldRefundDecision, v))
}

// RefundDecisionGTE applies the GTE predicate on the "refund_decision" field.
func RefundDecisionGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldRefundDecision, v))
}

// RefundDecisionLT applies the LT predicate on the "refund_decision" field.
func RefundDecisionLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldRefundDecision, v))
}

// RefundDecisionLTE applies the LTE predicate on the "refund_decision" field.
func RefundDecisionLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldRefundDecision, v))
}

// RefundDecisionContains applies the Contains predicate on the "refund_decision" field.
func RefundDecisionContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldRefundDecision, v))
}

// RefundDecisionHasPrefix applies the HasPrefix predicate on the "refund_decision" field.
func RefundDecisionHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldRefundDecision, v))
}

// RefundDecisionHasSuffix applies the HasSuffix predicate on the "refund_decision" field.
func RefundDecisionHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldRefundDecision, v))
}

// RefundDecisionEqualFold applies the EqualFold predicate on the "refund_decision" field.
func RefundDecisionEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldRefundDecision, v))
}

// RefundDecisionContainsFold applies the ContainsFold predicate on the "refund_decision" field.
func RefundDecisionContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldRefundDecision, v))
}

// ApprovedPrincipalAmountEQ applies the EQ predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountEQ(v float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountNEQ applies the NEQ predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountNEQ(v float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountIn applies the In predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountIn(vs ...float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldApprovedPrincipalAmount, vs...))
}

// ApprovedPrincipalAmountNotIn applies the NotIn predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountNotIn(vs ...float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldApprovedPrincipalAmount, vs...))
}

// ApprovedPrincipalAmountGT applies the GT predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountGT(v float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountGTE applies the GTE predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountGTE(v float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountLT applies the LT predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountLT(v float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountLTE applies the LTE predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountLTE(v float64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountIsNil applies the IsNil predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldApprovedPrincipalAmount))
}

// ApprovedPrincipalAmountNotNil applies the NotNil predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldApprovedPrincipalAmount))
}

// ReviewerIDEQ applies the EQ predicate on the "reviewer_id" field.
func ReviewerIDEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldReviewerID, v))
}

// ReviewerIDNEQ applies the NEQ predicate on the "reviewer_id" field.
func ReviewerIDNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldReviewerID, v))
}

// ReviewerIDIn applies the In predicate on the "reviewer_id" field.
func ReviewerIDIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldReviewerID, vs...))
}

// ReviewerIDNotIn applies the NotIn predicate on the "reviewer_id" field.
func ReviewerIDNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldReviewerID, vs...))
}

// ReviewerIDGT applies the GT predicate on the "reviewer_id" field.
func ReviewerIDGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldReviewerID, v))
}

// ReviewerIDGTE applies the GTE predicate on the "reviewer_id" field.
func ReviewerIDGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldReviewerID, v))
}

// ReviewerIDLT applies the LT predicate on the "reviewer_id" field.
func ReviewerIDLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldReviewerID, v))
}

// ReviewerIDLTE applies the LTE predicate on the "reviewer_id" field.
func ReviewerIDLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldReviewerID, v))
}

// ReviewerIDContains applies the Contains predicate on the "reviewer_id" field.
func ReviewerIDContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldReviewerID, v))
}

// ReviewerIDHasPrefix applies the HasPrefix predicate on the "reviewer_id" field.
func ReviewerIDHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldReviewerID, v))
}

// ReviewerIDHasSuffix applies the HasSuffix predicate on the "reviewer_id" field.
func ReviewerIDHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldReviewerID, v))
}

// ReviewerIDIsNil applies the IsNil predicate on the "reviewer_id" field.
func ReviewerIDIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldReviewerID))
}

// ReviewerIDNotNil applies the NotNil predicate on the "reviewer_id" field.
func ReviewerIDNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldReviewerID))
}

// ReviewerIDEqualFold applies the EqualFold predicate on the "reviewer_id" field.
func ReviewerIDEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldReviewerID, v))
}

// ReviewerIDContainsFold applies the ContainsFold predicate on the "reviewer_id" field.
func ReviewerIDContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldReviewerID, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldReviewedAt))
}

// ReopenCountEQ applies the EQ predicate on the "reopen_count" field.
func ReopenCountEQ(v int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldReopenCount, v))
}

// ReopenCountNEQ applies the NEQ predicate on the "reopen_count" field.
func ReopenCountNEQ(v int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldReopenCount, v))
}

// ReopenCountIn applies the In predicate on the "reopen_count" field.
func ReopenCountIn(vs ...int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldReopenCount, vs...))
}

// ReopenCountNotIn applies the NotIn predicate on the "reopen_count" field.
func ReopenCountNotIn(vs ...int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldReopenCount, vs...))
}

// ReopenCountGT applies the GT predicate on the "reopen_count" field.
func ReopenCountGT(v int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldReopenCount, v))
}

// ReopenCountGTE applies the GTE predicate on the "reopen_count" field.
func ReopenCountGTE(v int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldReopenCount, v))
}

// ReopenCountLT applies the LT predicate on the "reopen_count" field.
func ReopenCountLT(v int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldReopenCount, v))
}

// ReopenCountLTE applies the LTE predicate on the "reopen_count" field.
func ReopenCountLTE(v int) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldReopenCount, v))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldResolvedAt))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldClosedAt))
}

// LastUserActivityAtEQ applies the EQ predicate on the "last_user_activity_at" field.
func LastUserActivityAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastUserActivityAt, v))
}

// LastUserActivityAtNEQ applies the NEQ predicate on the "last_user_activity_at" field.
func LastUserActivityAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldLastUserActivityAt, v))
}

// LastUserActivityAtIn applies the In predicate on the "last_user_activity_at" field.
func LastUserActivityAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldLastUserActivityAt, vs...))
}

// LastUserActivityAtNotIn applies the NotIn predicate on the "last_user_activity_at" field.
func LastUserActivityAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldLastUserActivityAt, vs...))
}

// LastUserActivityAtGT applies the GT predicate on the "last_user_activity_at" field.
func LastUserActivityAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldLastUserActivityAt, v))
}

// LastUserActivityAtGTE applies the GTE predicate on the "last_user_activity_at" field.
func LastUserActivityAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldLastUserActivityAt, v))
}

// LastUserActivityAtLT applies the LT predicate on the "last_user_activity_at" field.
func LastUserActivityAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldLastUserActivityAt, v))
}

// LastUserActivityAtLTE applies the LTE predicate on the "last_user_activity_at" field.
func LastUserActivityAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldLastUserActivityAt, v))
}

// LastUserActivityAtIsNil applies the IsNil predicate on the "last_user_activity_at" field.
func LastUserActivityAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldLastUserActivityAt))
}

// LastUserActivityAtNotNil applies the NotNil predicate on the "last_user_activity_at" field.
func LastUserActivityAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldLastUserActivityAt))
}

// LastAdminActivityAtEQ applies the EQ predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastAdminActivityAt, v))
}

// LastAdminActivityAtNEQ applies the NEQ predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldLastAdminActivityAt, v))
}

// LastAdminActivityAtIn applies the In predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldLastAdminActivityAt, vs...))
}

// LastAdminActivityAtNotIn applies the NotIn predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldLastAdminActivityAt, vs...))
}

// LastAdminActivityAtGT applies the GT predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldLastAdminActivityAt, v))
}

// LastAdminActivityAtGTE applies the GTE predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldLastAdminActivityAt, v))
}

// LastAdminActivityAtLT applies the LT predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldLastAdminActivityAt, v))
}

// LastAdminActivityAtLTE applies the LTE predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldLastAdminActivityAt, v))
}

// LastAdminActivityAtIsNil applies the IsNil predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldLastAdminActivityAt))
}

// LastAdminActivityAtNotNil applies the NotNil predicate on the "last_admin_activity_at" field.
func LastAdminActivityAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldLastAdminActivityAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicket) predicate.SupportTicket {
	return predicate.SupportTicket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicket) predicate.SupportTicket {
	return predicate.SupportTicket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicket) predicate.SupportTicket {
	return predicate.SupportTicket(sql.NotPredicates(p))
}
