// Code generated by ent, DO NOT EDIT.

package paymentrefund

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentrefund type in the database.
	Label = "payment_refund"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTicketID holds the string denoting the ticket_id field in the database.
	FieldTicketID = "ticket_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldProviderRequestID holds the string denoting the provider_request_id field in the database.
	FieldProviderRequestID = "provider_request_id"
	// FieldProviderRefundID holds the string denoting the provider_refund_id field in the database.
	FieldProviderRefundID = "provider_refund_id"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldRequestedPrincipalAmount holds the string denoting the requested_principal_amount field in the database.
	FieldRequestedPrincipalAmount = "requested_principal_amount"
	// FieldPrincipalAmount holds the string denoting the principal_amount field in the database.
	FieldPrincipalAmount = "principal_amount"
	// FieldFeeAmount holds the string denoting the fee_amount field in the database.
	FieldFeeAmount = "fee_amount"
	// FieldGatewayAmount holds the string denoting the gateway_amount field in the database.
	FieldGatewayAmount = "gateway_amount"
	// FieldBasePoints holds the string denoting the base_points field in the database.
	FieldBasePoints = "base_points"
	// FieldBonusPoints holds the string denoting the bonus_points field in the database.
	FieldBonusPoints = "bonus_points"
	// FieldAffiliateRebatePoints holds the string denoting the affiliate_rebate_points field in the database.
	FieldAffiliateRebatePoints = "affiliate_rebate_points"
	// FieldBonusExpiredOffset holds the string denoting the bonus_expired_offset field in the database.
	FieldBonusExpiredOffset = "bonus_expired_offset"
	// FieldTargetPrincipalAmount holds the string denoting the target_principal_amount field in the database.
	FieldTargetPrincipalAmount = "target_principal_amount"
	// FieldTargetFeeAmount holds the string denoting the target_fee_amount field in the database.
	FieldTargetFeeAmount = "target_fee_amount"
	// FieldTargetBasePoints holds the string denoting the target_base_points field in the database.
	FieldTargetBasePoints = "target_base_points"
	// FieldTargetBonusPoints holds the string denoting the target_bonus_points field in the database.
	FieldTargetBonusPoints = "target_bonus_points"
	// FieldTargetAffiliatePoints holds the string denoting the target_affiliate_points field in the database.
	FieldTargetAffiliatePoints = "target_affiliate_points"
	// FieldWalletHoldID holds the string denoting the wallet_hold_id field in the database.
	FieldWalletHoldID = "wallet_hold_id"
	// FieldRequestedBy holds the string denoting the requested_by field in the database.
	FieldRequestedBy = "requested_by"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentrefund in the database.
	Table = "payment_refunds"
)

// Columns holds all SQL columns for paymentrefund fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldUserID,
	FieldTicketID,
	FieldSource,
	FieldStatus,
	FieldIdempotencyKey,
	FieldRequestFingerprint,
	FieldProviderRequestID,
	FieldProviderRefundID,
	FieldCurrency,
	FieldRequestedPrincipalAmount,
	FieldPrincipalAmount,
	FieldFeeAmount,
	FieldGatewayAmount,
	FieldBasePoints,
	FieldBonusPoints,
	FieldAffiliateRebatePoints,
	FieldBonusExpiredOffset,
	FieldTargetPrincipalAmount,
	FieldTargetFeeAmount,
	FieldTargetBasePoints,
	FieldTargetBonusPoints,
	FieldTargetAffiliatePoints,
	FieldWalletHoldID,
	FieldRequestedBy,
	FieldReason,
	FieldErrorCode,
	FieldErrorMessage,
	FieldSubmittedAt,
	FieldSettledAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultRequestFingerprint holds the default value on creation for the "request_fingerprint" field.
	DefaultRequestFingerprint string
	// RequestFingerprintValidator is a validator for the "request_fingerprint" field. It is called by the builders before save.
	RequestFingerprintValidator func(string) error
	// ProviderRequestIDValidator is a validator for the "provider_request_id" field. It is called by the builders before save.
	ProviderRequestIDValidator func(string) error
	// ProviderRefundIDValidator is a validator for the "provider_refund_id" field. It is called by the builders before save.
	ProviderRefundIDValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultRequestedPrincipalAmount holds the default value on creation for the "requested_principal_amount" field.
	DefaultRequestedPrincipalAmount float64
	// DefaultPrincipalAmount holds the default value on creation for the "principal_amount" field.
	DefaultPrincipalAmount float64
	// DefaultFeeAmount holds the default value on creation for the "fee_amount" field.
	DefaultFeeAmount float64
	// DefaultGatewayAmount holds the default value on creation for the "gateway_amount" field.
	DefaultGatewayAmount float64
	// DefaultBasePoints holds the default value on creation for the "base_points" field.
	DefaultBasePoints float64
	// DefaultBonusPoints holds the default value on creation for the "bonus_points" field.
	DefaultBonusPoints float64
	// DefaultAffiliateRebatePoints holds the default value on creation for the "affiliate_rebate_points" field.
	DefaultAffiliateRebatePoints float64
	// DefaultBonusExpiredOffset holds the default value on creation for the "bonus_expired_offset" field.
	DefaultBonusExpiredOffset float64
	// DefaultTargetPrincipalAmount holds the default value on creation for the "target_principal_amount" field.
	DefaultTargetPrincipalAmount float64
	// DefaultTargetFeeAmount holds the default value on creation for the "target_fee_amount" field.
	DefaultTargetFeeAmount float64
	// DefaultTargetBasePoints holds the default value on creation for the "target_base_points" field.
	DefaultTargetBasePoints float64
	// DefaultTargetBonusPoints holds the default value on creation for the "target_bonus_points" field.
	DefaultTargetBonusPoints float64
	// DefaultTargetAffiliatePoints holds the default value on creation for the "target_affiliate_points" field.
	DefaultTargetAffiliatePoints float64
	// DefaultReason holds the default value on creation for the "reason" field.
	DefaultReason string
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the PaymentRefund queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTicketID orders the results by the ticket_id field.
func ByTicketID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByRequestFingerprint orders the results by the request_fingerprint field.
func ByRequestFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestFingerprint, opts...).ToFunc()
}

// ByProviderRequestID orders the results by the provider_request_id field.
func ByProviderRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRequestID, opts...).ToFunc()
}

// ByProviderRefundID orders the results by the provider_refund_id field.
func ByProviderRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRefundID, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRequestedPrincipalAmount orders the results by the requested_principal_amount field.
func ByRequestedPrincipalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedPrincipalAmount, opts...).ToFunc()
}

// ByPrincipalAmount orders the results by the principal_amount field.
func ByPrincipalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalAmount, opts...).ToFunc()
}

// ByFeeAmount orders the results by the fee_amount field.
func ByFeeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeAmount, opts...).ToFunc()
}

// ByGatewayAmount orders the results by the gateway_amount field.
func ByGatewayAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayAmount, opts...).ToFunc()
}

// ByBasePoints orders the results by the base_points field.
func ByBasePoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBasePoints, opts...).ToFunc()
}

// ByBonusPoints orders the results by the bonus_points field.
func ByBonusPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBonusPoints, opts...).ToFunc()
}

// ByAffiliateRebatePoints orders the results by the affiliate_rebate_points field.
func ByAffiliateRebatePoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffiliateRebatePoints, opts...).ToFunc()
}

// ByBonusExpiredOffset orders the results by the bonus_expired_offset field.
func ByBonusExpiredOffset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBonusExpiredOffset, opts...).ToFunc()
}

// ByTargetPrincipalAmount orders the results by the target_principal_amount field.
func ByTargetPrincipalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetPrincipalAmount, opts...).ToFunc()
}

// ByTargetFeeAmount orders the results by the target_fee_amount field.
func ByTargetFeeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetFeeAmount, opts...).ToFunc()
}

// ByTargetBasePoints orders the results by the target_base_points field.
func ByTargetBasePoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetBasePoints, opts...).ToFunc()
}

// ByTargetBonusPoints orders the results by the target_bonus_points field.
func ByTargetBonusPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetBonusPoints, opts...).ToFunc()
}

// ByTargetAffiliatePoints orders the results by the target_affiliate_points field.
func ByTargetAffiliatePoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetAffiliatePoints, opts...).ToFunc()
}

// ByWalletHoldID orders the results by the wallet_hold_id field.
func ByWalletHoldID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletHoldID, opts...).ToFunc()
}

// ByRequestedBy orders the results by the requested_by field.
func ByRequestedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedBy, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
