// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/AsukaCC/EasySub2api/ent/accountmodelrule"
)

// AccountModelRule is the model entity for the AccountModelRule schema.
type AccountModelRule struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Mapping holds the value of the "mapping" field.
	Mapping map[string]string `json:"mapping,omitempty"`
	// ReasoningEfforts holds the value of the "reasoning_efforts" field.
	ReasoningEfforts map[string]string `json:"reasoning_efforts,omitempty"`
	// Whitelist holds the value of the "whitelist" field.
	Whitelist    []string `json:"whitelist,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountModelRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountmodelrule.FieldMapping, accountmodelrule.FieldReasoningEfforts, accountmodelrule.FieldWhitelist:
			values[i] = new([]byte)
		case accountmodelrule.FieldID, accountmodelrule.FieldName, accountmodelrule.FieldDescription, accountmodelrule.FieldPlatform:
			values[i] = new(sql.NullString)
		case accountmodelrule.FieldCreatedAt, accountmodelrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountModelRule fields.
func (_m *AccountModelRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountmodelrule.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case accountmodelrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountmodelrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountmodelrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case accountmodelrule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case accountmodelrule.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case accountmodelrule.FieldMapping:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field mapping", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Mapping); err != nil {
					return fmt.Errorf("unmarshal field mapping: %w", err)
				}
			}
		case accountmodelrule.FieldReasoningEfforts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_efforts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ReasoningEfforts); err != nil {
					return fmt.Errorf("unmarshal field reasoning_efforts: %w", err)
				}
			}
		case accountmodelrule.FieldWhitelist:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field whitelist", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Whitelist); err != nil {
					return fmt.Errorf("unmarshal field whitelist: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountModelRule.
// This includes values selected through modifiers, order, etc.
func (_m *AccountModelRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountModelRule.
// Note that you need to call AccountModelRule.Unwrap() before calling this method if this AccountModelRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountModelRule) Update() *AccountModelRuleUpdateOne {
	return NewAccountModelRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountModelRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountModelRule) Unwrap() *AccountModelRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountModelRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountModelRule) String() string {
	var builder strings.Builder
	builder.WriteString("AccountModelRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("mapping=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mapping))
	builder.WriteString(", ")
	builder.WriteString("reasoning_efforts=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReasoningEfforts))
	builder.WriteString(", ")
	builder.WriteString("whitelist=")
	builder.WriteString(fmt.Sprintf("%v", _m.Whitelist))
	builder.WriteByte(')')
	return builder.String()
}

// AccountModelRules is a parsable slice of AccountModelRule.
type AccountModelRules []*AccountModelRule
