// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/AsukaCC/EasySub2api/ent/accountmodelrule"
	"github.com/AsukaCC/EasySub2api/ent/predicate"
)

// AccountModelRuleUpdate is the builder for updating AccountModelRule entities.
type AccountModelRuleUpdate struct {
	config
	hooks    []Hook
	mutation *AccountModelRuleMutation
}

// Where appends a list predicates to the AccountModelRuleUpdate builder.
func (_u *AccountModelRuleUpdate) Where(ps ...predicate.AccountModelRule) *AccountModelRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountModelRuleUpdate) SetUpdatedAt(v time.Time) *AccountModelRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountModelRuleUpdate) SetName(v string) *AccountModelRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountModelRuleUpdate) SetNillableName(v *string) *AccountModelRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountModelRuleUpdate) SetDescription(v string) *AccountModelRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountModelRuleUpdate) SetNillableDescription(v *string) *AccountModelRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountModelRuleUpdate) ClearDescription() *AccountModelRuleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AccountModelRuleUpdate) SetPlatform(v string) *AccountModelRuleUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AccountModelRuleUpdate) SetNillablePlatform(v *string) *AccountModelRuleUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetMapping sets the "mapping" field.
func (_u *AccountModelRuleUpdate) SetMapping(v map[string]string) *AccountModelRuleUpdate {
	_u.mutation.SetMapping(v)
	return _u
}

// SetReasoningEfforts sets the "reasoning_efforts" field.
func (_u *AccountModelRuleUpdate) SetReasoningEfforts(v map[string]string) *AccountModelRuleUpdate {
	_u.mutation.SetReasoningEfforts(v)
	return _u
}

// SetWhitelist sets the "whitelist" field.
func (_u *AccountModelRuleUpdate) SetWhitelist(v []string) *AccountModelRuleUpdate {
	_u.mutation.SetWhitelist(v)
	return _u
}

// AppendWhitelist appends value to the "whitelist" field.
func (_u *AccountModelRuleUpdate) AppendWhitelist(v []string) *AccountModelRuleUpdate {
	_u.mutation.AppendWhitelist(v)
	return _u
}

// Mutation returns the AccountModelRuleMutation object of the builder.
func (_u *AccountModelRuleUpdate) Mutation() *AccountModelRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountModelRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountModelRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountModelRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountModelRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountModelRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountmodelrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountModelRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountmodelrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountModelRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := accountmodelrule.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AccountModelRule.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountModelRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountmodelrule.Table, accountmodelrule.Columns, sqlgraph.NewFieldSpec(accountmodelrule.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountmodelrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountmodelrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(accountmodelrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(accountmodelrule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(accountmodelrule.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mapping(); ok {
		_spec.SetField(accountmodelrule.FieldMapping, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ReasoningEfforts(); ok {
		_spec.SetField(accountmodelrule.FieldReasoningEfforts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Whitelist(); ok {
		_spec.SetField(accountmodelrule.FieldWhitelist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWhitelist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accountmodelrule.FieldWhitelist, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountmodelrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountModelRuleUpdateOne is the builder for updating a single AccountModelRule entity.
type AccountModelRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountModelRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountModelRuleUpdateOne) SetUpdatedAt(v time.Time) *AccountModelRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountModelRuleUpdateOne) SetName(v string) *AccountModelRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountModelRuleUpdateOne) SetNillableName(v *string) *AccountModelRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountModelRuleUpdateOne) SetDescription(v string) *AccountModelRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountModelRuleUpdateOne) SetNillableDescription(v *string) *AccountModelRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountModelRuleUpdateOne) ClearDescription() *AccountModelRuleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *AccountModelRuleUpdateOne) SetPlatform(v string) *AccountModelRuleUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *AccountModelRuleUpdateOne) SetNillablePlatform(v *string) *AccountModelRuleUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetMapping sets the "mapping" field.
func (_u *AccountModelRuleUpdateOne) SetMapping(v map[string]string) *AccountModelRuleUpdateOne {
	_u.mutation.SetMapping(v)
	return _u
}

// SetReasoningEfforts sets the "reasoning_efforts" field.
func (_u *AccountModelRuleUpdateOne) SetReasoningEfforts(v map[string]string) *AccountModelRuleUpdateOne {
	_u.mutation.SetReasoningEfforts(v)
	return _u
}

// SetWhitelist sets the "whitelist" field.
func (_u *AccountModelRuleUpdateOne) SetWhitelist(v []string) *AccountModelRuleUpdateOne {
	_u.mutation.SetWhitelist(v)
	return _u
}

// AppendWhitelist appends value to the "whitelist" field.
func (_u *AccountModelRuleUpdateOne) AppendWhitelist(v []string) *AccountModelRuleUpdateOne {
	_u.mutation.AppendWhitelist(v)
	return _u
}

// Mutation returns the AccountModelRuleMutation object of the builder.
func (_u *AccountModelRuleUpdateOne) Mutation() *AccountModelRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountModelRuleUpdate builder.
func (_u *AccountModelRuleUpdateOne) Where(ps ...predicate.AccountModelRule) *AccountModelRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountModelRuleUpdateOne) Select(field string, fields ...string) *AccountModelRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountModelRule entity.
func (_u *AccountModelRuleUpdateOne) Save(ctx context.Context) (*AccountModelRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountModelRuleUpdateOne) SaveX(ctx context.Context) *AccountModelRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountModelRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountModelRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountModelRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountmodelrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountModelRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accountmodelrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountModelRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := accountmodelrule.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AccountModelRule.platform": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountModelRuleUpdateOne) sqlSave(ctx context.Context) (_node *AccountModelRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountmodelrule.Table, accountmodelrule.Columns, sqlgraph.NewFieldSpec(accountmodelrule.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountModelRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountmodelrule.FieldID)
		for _, f := range fields {
			if !accountmodelrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountmodelrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountmodelrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accountmodelrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(accountmodelrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(accountmodelrule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(accountmodelrule.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mapping(); ok {
		_spec.SetField(accountmodelrule.FieldMapping, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ReasoningEfforts(); ok {
		_spec.SetField(accountmodelrule.FieldReasoningEfforts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Whitelist(); ok {
		_spec.SetField(accountmodelrule.FieldWhitelist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedWhitelist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, accountmodelrule.FieldWhitelist, value)
		})
	}
	_node = &AccountModelRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountmodelrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
