// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AsukaCC/EasySub2api/ent/accountmodelrule"
)

// AccountModelRuleCreate is the builder for creating a AccountModelRule entity.
type AccountModelRuleCreate struct {
	config
	mutation *AccountModelRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountModelRuleCreate) SetCreatedAt(v time.Time) *AccountModelRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountModelRuleCreate) SetNillableCreatedAt(v *time.Time) *AccountModelRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountModelRuleCreate) SetUpdatedAt(v time.Time) *AccountModelRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountModelRuleCreate) SetNillableUpdatedAt(v *time.Time) *AccountModelRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AccountModelRuleCreate) SetName(v string) *AccountModelRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AccountModelRuleCreate) SetDescription(v string) *AccountModelRuleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AccountModelRuleCreate) SetNillableDescription(v *string) *AccountModelRuleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *AccountModelRuleCreate) SetPlatform(v string) *AccountModelRuleCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetMapping sets the "mapping" field.
func (_c *AccountModelRuleCreate) SetMapping(v map[string]string) *AccountModelRuleCreate {
	_c.mutation.SetMapping(v)
	return _c
}

// SetReasoningEfforts sets the "reasoning_efforts" field.
func (_c *AccountModelRuleCreate) SetReasoningEfforts(v map[string]string) *AccountModelRuleCreate {
	_c.mutation.SetReasoningEfforts(v)
	return _c
}

// SetWhitelist sets the "whitelist" field.
func (_c *AccountModelRuleCreate) SetWhitelist(v []string) *AccountModelRuleCreate {
	_c.mutation.SetWhitelist(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AccountModelRuleCreate) SetID(v string) *AccountModelRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccountModelRuleCreate) SetNillableID(v *string) *AccountModelRuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AccountModelRuleMutation object of the builder.
func (_c *AccountModelRuleCreate) Mutation() *AccountModelRuleMutation {
	return _c.mutation
}

// Save creates the AccountModelRule in the database.
func (_c *AccountModelRuleCreate) Save(ctx context.Context) (*AccountModelRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountModelRuleCreate) SaveX(ctx context.Context) *AccountModelRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountModelRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountModelRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountModelRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountmodelrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountmodelrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := accountmodelrule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountModelRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountModelRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountModelRule.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccountModelRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := accountmodelrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountModelRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "AccountModelRule.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := accountmodelrule.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "AccountModelRule.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mapping(); !ok {
		return &ValidationError{Name: "mapping", err: errors.New(`ent: missing required field "AccountModelRule.mapping"`)}
	}
	if _, ok := _c.mutation.ReasoningEfforts(); !ok {
		return &ValidationError{Name: "reasoning_efforts", err: errors.New(`ent: missing required field "AccountModelRule.reasoning_efforts"`)}
	}
	if _, ok := _c.mutation.Whitelist(); !ok {
		return &ValidationError{Name: "whitelist", err: errors.New(`ent: missing required field "AccountModelRule.whitelist"`)}
	}
	return nil
}

func (_c *AccountModelRuleCreate) sqlSave(ctx context.Context) (*AccountModelRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AccountModelRule.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountModelRuleCreate) createSpec() (*AccountModelRule, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountModelRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountmodelrule.Table, sqlgraph.NewFieldSpec(accountmodelrule.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountmodelrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountmodelrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accountmodelrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(accountmodelrule.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(accountmodelrule.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Mapping(); ok {
		_spec.SetField(accountmodelrule.FieldMapping, field.TypeJSON, value)
		_node.Mapping = value
	}
	if value, ok := _c.mutation.ReasoningEfforts(); ok {
		_spec.SetField(accountmodelrule.FieldReasoningEfforts, field.TypeJSON, value)
		_node.ReasoningEfforts = value
	}
	if value, ok := _c.mutation.Whitelist(); ok {
		_spec.SetField(accountmodelrule.FieldWhitelist, field.TypeJSON, value)
		_node.Whitelist = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountModelRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountModelRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountModelRuleCreate) OnConflict(opts ...sql.ConflictOption) *AccountModelRuleUpsertOne {
	_c.conflict = opts
	return &AccountModelRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountModelRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountModelRuleCreate) OnConflictColumns(columns ...string) *AccountModelRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountModelRuleUpsertOne{
		create: _c,
	}
}

type (
	// AccountModelRuleUpsertOne is the builder for "upsert"-ing
	//  one AccountModelRule node.
	AccountModelRuleUpsertOne struct {
		create *AccountModelRuleCreate
	}

	// AccountModelRuleUpsert is the "OnConflict" setter.
	AccountModelRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountModelRuleUpsert) SetUpdatedAt(v time.Time) *AccountModelRuleUpsert {
	u.Set(accountmodelrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountModelRuleUpsert) UpdateUpdatedAt() *AccountModelRuleUpsert {
	u.SetExcluded(accountmodelrule.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *AccountModelRuleUpsert) SetName(v string) *AccountModelRuleUpsert {
	u.Set(accountmodelrule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountModelRuleUpsert) UpdateName() *AccountModelRuleUpsert {
	u.SetExcluded(accountmodelrule.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *AccountModelRuleUpsert) SetDescription(v string) *AccountModelRuleUpsert {
	u.Set(accountmodelrule.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountModelRuleUpsert) UpdateDescription() *AccountModelRuleUpsert {
	u.SetExcluded(accountmodelrule.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AccountModelRuleUpsert) ClearDescription() *AccountModelRuleUpsert {
	u.SetNull(accountmodelrule.FieldDescription)
	return u
}

// SetPlatform sets the "platform" field.
func (u *AccountModelRuleUpsert) SetPlatform(v string) *AccountModelRuleUpsert {
	u.Set(accountmodelrule.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AccountModelRuleUpsert) UpdatePlatform() *AccountModelRuleUpsert {
	u.SetExcluded(accountmodelrule.FieldPlatform)
	return u
}

// SetMapping sets the "mapping" field.
func (u *AccountModelRuleUpsert) SetMapping(v map[string]string) *AccountModelRuleUpsert {
	u.Set(accountmodelrule.FieldMapping, v)
	return u
}

// UpdateMapping sets the "mapping" field to the value that was provided on create.
func (u *AccountModelRuleUpsert) UpdateMapping() *AccountModelRuleUpsert {
	u.SetExcluded(accountmodelrule.FieldMapping)
	return u
}

// SetReasoningEfforts sets the "reasoning_efforts" field.
func (u *AccountModelRuleUpsert) SetReasoningEfforts(v map[string]string) *AccountModelRuleUpsert {
	u.Set(accountmodelrule.FieldReasoningEfforts, v)
	return u
}

// UpdateReasoningEfforts sets the "reasoning_efforts" field to the value that was provided on create.
func (u *AccountModelRuleUpsert) UpdateReasoningEfforts() *AccountModelRuleUpsert {
	u.SetExcluded(accountmodelrule.FieldReasoningEfforts)
	return u
}

// SetWhitelist sets the "whitelist" field.
func (u *AccountModelRuleUpsert) SetWhitelist(v []string) *AccountModelRuleUpsert {
	u.Set(accountmodelrule.FieldWhitelist, v)
	return u
}

// UpdateWhitelist sets the "whitelist" field to the value that was provided on create.
func (u *AccountModelRuleUpsert) UpdateWhitelist() *AccountModelRuleUpsert {
	u.SetExcluded(accountmodelrule.FieldWhitelist)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AccountModelRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountmodelrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountModelRuleUpsertOne) UpdateNewValues() *AccountModelRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(accountmodelrule.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountmodelrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountModelRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountModelRuleUpsertOne) Ignore() *AccountModelRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountModelRuleUpsertOne) DoNothing() *AccountModelRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountModelRuleCreate.OnConflict
// documentation for more info.
func (u *AccountModelRuleUpsertOne) Update(set func(*AccountModelRuleUpsert)) *AccountModelRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountModelRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountModelRuleUpsertOne) SetUpdatedAt(v time.Time) *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountModelRuleUpsertOne) UpdateUpdatedAt() *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountModelRuleUpsertOne) SetName(v string) *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountModelRuleUpsertOne) UpdateName() *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *AccountModelRuleUpsertOne) SetDescription(v string) *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountModelRuleUpsertOne) UpdateDescription() *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AccountModelRuleUpsertOne) ClearDescription() *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.ClearDescription()
	})
}

// SetPlatform sets the "platform" field.
func (u *AccountModelRuleUpsertOne) SetPlatform(v string) *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AccountModelRuleUpsertOne) UpdatePlatform() *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdatePlatform()
	})
}

// SetMapping sets the "mapping" field.
func (u *AccountModelRuleUpsertOne) SetMapping(v map[string]string) *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetMapping(v)
	})
}

// UpdateMapping sets the "mapping" field to the value that was provided on create.
func (u *AccountModelRuleUpsertOne) UpdateMapping() *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateMapping()
	})
}

// SetReasoningEfforts sets the "reasoning_efforts" field.
func (u *AccountModelRuleUpsertOne) SetReasoningEfforts(v map[string]string) *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetReasoningEfforts(v)
	})
}

// UpdateReasoningEfforts sets the "reasoning_efforts" field to the value that was provided on create.
func (u *AccountModelRuleUpsertOne) UpdateReasoningEfforts() *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateReasoningEfforts()
	})
}

// SetWhitelist sets the "whitelist" field.
func (u *AccountModelRuleUpsertOne) SetWhitelist(v []string) *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetWhitelist(v)
	})
}

// UpdateWhitelist sets the "whitelist" field to the value that was provided on create.
func (u *AccountModelRuleUpsertOne) UpdateWhitelist() *AccountModelRuleUpsertOne {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateWhitelist()
	})
}

// Exec executes the query.
func (u *AccountModelRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountModelRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountModelRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountModelRuleUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccountModelRuleUpsertOne.ID is not supported by MySQL driver. Use AccountModelRuleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountModelRuleUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountModelRuleCreateBulk is the builder for creating many AccountModelRule entities in bulk.
type AccountModelRuleCreateBulk struct {
	config
	err      error
	builders []*AccountModelRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountModelRule entities in the database.
func (_c *AccountModelRuleCreateBulk) Save(ctx context.Context) ([]*AccountModelRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountModelRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountModelRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountModelRuleCreateBulk) SaveX(ctx context.Context) []*AccountModelRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountModelRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountModelRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountModelRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountModelRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountModelRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountModelRuleUpsertBulk {
	_c.conflict = opts
	return &AccountModelRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountModelRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountModelRuleCreateBulk) OnConflictColumns(columns ...string) *AccountModelRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountModelRuleUpsertBulk{
		create: _c,
	}
}

// AccountModelRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountModelRule nodes.
type AccountModelRuleUpsertBulk struct {
	create *AccountModelRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountModelRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountmodelrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountModelRuleUpsertBulk) UpdateNewValues() *AccountModelRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(accountmodelrule.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountmodelrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountModelRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountModelRuleUpsertBulk) Ignore() *AccountModelRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountModelRuleUpsertBulk) DoNothing() *AccountModelRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountModelRuleCreateBulk.OnConflict
// documentation for more info.
func (u *AccountModelRuleUpsertBulk) Update(set func(*AccountModelRuleUpsert)) *AccountModelRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountModelRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountModelRuleUpsertBulk) SetUpdatedAt(v time.Time) *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountModelRuleUpsertBulk) UpdateUpdatedAt() *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *AccountModelRuleUpsertBulk) SetName(v string) *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountModelRuleUpsertBulk) UpdateName() *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *AccountModelRuleUpsertBulk) SetDescription(v string) *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountModelRuleUpsertBulk) UpdateDescription() *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AccountModelRuleUpsertBulk) ClearDescription() *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.ClearDescription()
	})
}

// SetPlatform sets the "platform" field.
func (u *AccountModelRuleUpsertBulk) SetPlatform(v string) *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *AccountModelRuleUpsertBulk) UpdatePlatform() *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdatePlatform()
	})
}

// SetMapping sets the "mapping" field.
func (u *AccountModelRuleUpsertBulk) SetMapping(v map[string]string) *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetMapping(v)
	})
}

// UpdateMapping sets the "mapping" field to the value that was provided on create.
func (u *AccountModelRuleUpsertBulk) UpdateMapping() *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateMapping()
	})
}

// SetReasoningEfforts sets the "reasoning_efforts" field.
func (u *AccountModelRuleUpsertBulk) SetReasoningEfforts(v map[string]string) *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetReasoningEfforts(v)
	})
}

// UpdateReasoningEfforts sets the "reasoning_efforts" field to the value that was provided on create.
func (u *AccountModelRuleUpsertBulk) UpdateReasoningEfforts() *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateReasoningEfforts()
	})
}

// SetWhitelist sets the "whitelist" field.
func (u *AccountModelRuleUpsertBulk) SetWhitelist(v []string) *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.SetWhitelist(v)
	})
}

// UpdateWhitelist sets the "whitelist" field to the value that was provided on create.
func (u *AccountModelRuleUpsertBulk) UpdateWhitelist() *AccountModelRuleUpsertBulk {
	return u.Update(func(s *AccountModelRuleUpsert) {
		s.UpdateWhitelist()
	})
}

// Exec executes the query.
func (u *AccountModelRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountModelRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountModelRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountModelRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
