// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/AsukaCC/EasySub2api/ent/paymentrefund"
)

// PaymentRefund is the model entity for the PaymentRefund schema.
type PaymentRefund struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID string `json:"order_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID *string `json:"ticket_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint string `json:"request_fingerprint,omitempty"`
	// ProviderRequestID holds the value of the "provider_request_id" field.
	ProviderRequestID string `json:"provider_request_id,omitempty"`
	// ProviderRefundID holds the value of the "provider_refund_id" field.
	ProviderRefundID *string `json:"provider_refund_id,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// RequestedPrincipalAmount holds the value of the "requested_principal_amount" field.
	RequestedPrincipalAmount float64 `json:"requested_principal_amount,omitempty"`
	// PrincipalAmount holds the value of the "principal_amount" field.
	PrincipalAmount float64 `json:"principal_amount,omitempty"`
	// FeeAmount holds the value of the "fee_amount" field.
	FeeAmount float64 `json:"fee_amount,omitempty"`
	// RefundFeeRate holds the value of the "refund_fee_rate" field.
	RefundFeeRate float64 `json:"refund_fee_rate,omitempty"`
	// RefundFeeAmount holds the value of the "refund_fee_amount" field.
	RefundFeeAmount float64 `json:"refund_fee_amount,omitempty"`
	// GatewayAmount holds the value of the "gateway_amount" field.
	GatewayAmount float64 `json:"gateway_amount,omitempty"`
	// BasePoints holds the value of the "base_points" field.
	BasePoints float64 `json:"base_points,omitempty"`
	// BonusPoints holds the value of the "bonus_points" field.
	BonusPoints float64 `json:"bonus_points,omitempty"`
	// AffiliateRebatePoints holds the value of the "affiliate_rebate_points" field.
	AffiliateRebatePoints float64 `json:"affiliate_rebate_points,omitempty"`
	// BonusExpiredOffset holds the value of the "bonus_expired_offset" field.
	BonusExpiredOffset float64 `json:"bonus_expired_offset,omitempty"`
	// TargetPrincipalAmount holds the value of the "target_principal_amount" field.
	TargetPrincipalAmount float64 `json:"target_principal_amount,omitempty"`
	// TargetFeeAmount holds the value of the "target_fee_amount" field.
	TargetFeeAmount float64 `json:"target_fee_amount,omitempty"`
	// TargetRefundFeeAmount holds the value of the "target_refund_fee_amount" field.
	TargetRefundFeeAmount float64 `json:"target_refund_fee_amount,omitempty"`
	// TargetBasePoints holds the value of the "target_base_points" field.
	TargetBasePoints float64 `json:"target_base_points,omitempty"`
	// TargetBonusPoints holds the value of the "target_bonus_points" field.
	TargetBonusPoints float64 `json:"target_bonus_points,omitempty"`
	// TargetAffiliatePoints holds the value of the "target_affiliate_points" field.
	TargetAffiliatePoints float64 `json:"target_affiliate_points,omitempty"`
	// WalletHoldID holds the value of the "wallet_hold_id" field.
	WalletHoldID *string `json:"wallet_hold_id,omitempty"`
	// RequestedBy holds the value of the "requested_by" field.
	RequestedBy *string `json:"requested_by,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentRefund) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentrefund.FieldRequestedPrincipalAmount, paymentrefund.FieldPrincipalAmount, paymentrefund.FieldFeeAmount, paymentrefund.FieldRefundFeeRate, paymentrefund.FieldRefundFeeAmount, paymentrefund.FieldGatewayAmount, paymentrefund.FieldBasePoints, paymentrefund.FieldBonusPoints, paymentrefund.FieldAffiliateRebatePoints, paymentrefund.FieldBonusExpiredOffset, paymentrefund.FieldTargetPrincipalAmount, paymentrefund.FieldTargetFeeAmount, paymentrefund.FieldTargetRefundFeeAmount, paymentrefund.FieldTargetBasePoints, paymentrefund.FieldTargetBonusPoints, paymentrefund.FieldTargetAffiliatePoints:
			values[i] = new(sql.NullFloat64)
		case paymentrefund.FieldID, paymentrefund.FieldOrderID, paymentrefund.FieldUserID, paymentrefund.FieldTicketID, paymentrefund.FieldSource, paymentrefund.FieldStatus, paymentrefund.FieldIdempotencyKey, paymentrefund.FieldRequestFingerprint, paymentrefund.FieldProviderRequestID, paymentrefund.FieldProviderRefundID, paymentrefund.FieldCurrency, paymentrefund.FieldWalletHoldID, paymentrefund.FieldRequestedBy, paymentrefund.FieldReason, paymentrefund.FieldErrorCode, paymentrefund.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case paymentrefund.FieldSubmittedAt, paymentrefund.FieldSettledAt, paymentrefund.FieldCreatedAt, paymentrefund.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentRefund fields.
func (_m *PaymentRefund) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentrefund.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case paymentrefund.FieldOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.String
			}
		case paymentrefund.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case paymentrefund.FieldTicketID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = new(string)
				*_m.TicketID = value.String
			}
		case paymentrefund.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case paymentrefund.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentrefund.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case paymentrefund.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = value.String
			}
		case paymentrefund.FieldProviderRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_request_id", values[i])
			} else if value.Valid {
				_m.ProviderRequestID = value.String
			}
		case paymentrefund.FieldProviderRefundID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_refund_id", values[i])
			} else if value.Valid {
				_m.ProviderRefundID = new(string)
				*_m.ProviderRefundID = value.String
			}
		case paymentrefund.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentrefund.FieldRequestedPrincipalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field requested_principal_amount", values[i])
			} else if value.Valid {
				_m.RequestedPrincipalAmount = value.Float64
			}
		case paymentrefund.FieldPrincipalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field principal_amount", values[i])
			} else if value.Valid {
				_m.PrincipalAmount = value.Float64
			}
		case paymentrefund.FieldFeeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_amount", values[i])
			} else if value.Valid {
				_m.FeeAmount = value.Float64
			}
		case paymentrefund.FieldRefundFeeRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_fee_rate", values[i])
			} else if value.Valid {
				_m.RefundFeeRate = value.Float64
			}
		case paymentrefund.FieldRefundFeeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_fee_amount", values[i])
			} else if value.Valid {
				_m.RefundFeeAmount = value.Float64
			}
		case paymentrefund.FieldGatewayAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gateway_amount", values[i])
			} else if value.Valid {
				_m.GatewayAmount = value.Float64
			}
		case paymentrefund.FieldBasePoints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_points", values[i])
			} else if value.Valid {
				_m.BasePoints = value.Float64
			}
		case paymentrefund.FieldBonusPoints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_points", values[i])
			} else if value.Valid {
				_m.BonusPoints = value.Float64
			}
		case paymentrefund.FieldAffiliateRebatePoints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field affiliate_rebate_points", values[i])
			} else if value.Valid {
				_m.AffiliateRebatePoints = value.Float64
			}
		case paymentrefund.FieldBonusExpiredOffset:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_expired_offset", values[i])
			} else if value.Valid {
				_m.BonusExpiredOffset = value.Float64
			}
		case paymentrefund.FieldTargetPrincipalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target_principal_amount", values[i])
			} else if value.Valid {
				_m.TargetPrincipalAmount = value.Float64
			}
		case paymentrefund.FieldTargetFeeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target_fee_amount", values[i])
			} else if value.Valid {
				_m.TargetFeeAmount = value.Float64
			}
		case paymentrefund.FieldTargetRefundFeeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target_refund_fee_amount", values[i])
			} else if value.Valid {
				_m.TargetRefundFeeAmount = value.Float64
			}
		case paymentrefund.FieldTargetBasePoints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target_base_points", values[i])
			} else if value.Valid {
				_m.TargetBasePoints = value.Float64
			}
		case paymentrefund.FieldTargetBonusPoints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target_bonus_points", values[i])
			} else if value.Valid {
				_m.TargetBonusPoints = value.Float64
			}
		case paymentrefund.FieldTargetAffiliatePoints:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target_affiliate_points", values[i])
			} else if value.Valid {
				_m.TargetAffiliatePoints = value.Float64
			}
		case paymentrefund.FieldWalletHoldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_hold_id", values[i])
			} else if value.Valid {
				_m.WalletHoldID = new(string)
				*_m.WalletHoldID = value.String
			}
		case paymentrefund.FieldRequestedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_by", values[i])
			} else if value.Valid {
				_m.RequestedBy = new(string)
				*_m.RequestedBy = value.String
			}
		case paymentrefund.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case paymentrefund.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = value.String
			}
		case paymentrefund.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case paymentrefund.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case paymentrefund.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		case paymentrefund.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentrefund.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentRefund.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentRefund) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentRefund.
// Note that you need to call PaymentRefund.Unwrap() before calling this method if this PaymentRefund
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentRefund) Update() *PaymentRefundUpdateOne {
	return NewPaymentRefundClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentRefund entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentRefund) Unwrap() *PaymentRefund {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentRefund is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentRefund) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentRefund(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_id=")
	builder.WriteString(_m.OrderID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	if v := _m.TicketID; v != nil {
		builder.WriteString("ticket_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("request_fingerprint=")
	builder.WriteString(_m.RequestFingerprint)
	builder.WriteString(", ")
	builder.WriteString("provider_request_id=")
	builder.WriteString(_m.ProviderRequestID)
	builder.WriteString(", ")
	if v := _m.ProviderRefundID; v != nil {
		builder.WriteString("provider_refund_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("requested_principal_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedPrincipalAmount))
	builder.WriteString(", ")
	builder.WriteString("principal_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrincipalAmount))
	builder.WriteString(", ")
	builder.WriteString("fee_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeAmount))
	builder.WriteString(", ")
	builder.WriteString("refund_fee_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundFeeRate))
	builder.WriteString(", ")
	builder.WriteString("refund_fee_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundFeeAmount))
	builder.WriteString(", ")
	builder.WriteString("gateway_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.GatewayAmount))
	builder.WriteString(", ")
	builder.WriteString("base_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.BasePoints))
	builder.WriteString(", ")
	builder.WriteString("bonus_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusPoints))
	builder.WriteString(", ")
	builder.WriteString("affiliate_rebate_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.AffiliateRebatePoints))
	builder.WriteString(", ")
	builder.WriteString("bonus_expired_offset=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusExpiredOffset))
	builder.WriteString(", ")
	builder.WriteString("target_principal_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetPrincipalAmount))
	builder.WriteString(", ")
	builder.WriteString("target_fee_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetFeeAmount))
	builder.WriteString(", ")
	builder.WriteString("target_refund_fee_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetRefundFeeAmount))
	builder.WriteString(", ")
	builder.WriteString("target_base_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetBasePoints))
	builder.WriteString(", ")
	builder.WriteString("target_bonus_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetBonusPoints))
	builder.WriteString(", ")
	builder.WriteString("target_affiliate_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetAffiliatePoints))
	builder.WriteString(", ")
	if v := _m.WalletHoldID; v != nil {
		builder.WriteString("wallet_hold_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestedBy; v != nil {
		builder.WriteString("requested_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(_m.ErrorCode)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentRefunds is a parsable slice of PaymentRefund.
type PaymentRefunds []*PaymentRefund
