// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AsukaCC/EasySub2api/ent/refundticket"
)

// RefundTicketCreate is the builder for creating a RefundTicket entity.
type RefundTicketCreate struct {
	config
	mutation *RefundTicketMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderID sets the "order_id" field.
func (_c *RefundTicketCreate) SetOrderID(v string) *RefundTicketCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RefundTicketCreate) SetUserID(v string) *RefundTicketCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRefundID sets the "refund_id" field.
func (_c *RefundTicketCreate) SetRefundID(v string) *RefundTicketCreate {
	_c.mutation.SetRefundID(v)
	return _c
}

// SetNillableRefundID sets the "refund_id" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableRefundID(v *string) *RefundTicketCreate {
	if v != nil {
		_c.SetRefundID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RefundTicketCreate) SetStatus(v string) *RefundTicketCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableStatus(v *string) *RefundTicketCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetComment sets the "comment" field.
func (_c *RefundTicketCreate) SetComment(v string) *RefundTicketCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableComment(v *string) *RefundTicketCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetApprovedPrincipalAmount sets the "approved_principal_amount" field.
func (_c *RefundTicketCreate) SetApprovedPrincipalAmount(v float64) *RefundTicketCreate {
	_c.mutation.SetApprovedPrincipalAmount(v)
	return _c
}

// SetNillableApprovedPrincipalAmount sets the "approved_principal_amount" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableApprovedPrincipalAmount(v *float64) *RefundTicketCreate {
	if v != nil {
		_c.SetApprovedPrincipalAmount(*v)
	}
	return _c
}

// SetReviewerID sets the "reviewer_id" field.
func (_c *RefundTicketCreate) SetReviewerID(v string) *RefundTicketCreate {
	_c.mutation.SetReviewerID(v)
	return _c
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableReviewerID(v *string) *RefundTicketCreate {
	if v != nil {
		_c.SetReviewerID(*v)
	}
	return _c
}

// SetReviewNote sets the "review_note" field.
func (_c *RefundTicketCreate) SetReviewNote(v string) *RefundTicketCreate {
	_c.mutation.SetReviewNote(v)
	return _c
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableReviewNote(v *string) *RefundTicketCreate {
	if v != nil {
		_c.SetReviewNote(*v)
	}
	return _c
}

// SetAffiliateAction sets the "affiliate_action" field.
func (_c *RefundTicketCreate) SetAffiliateAction(v string) *RefundTicketCreate {
	_c.mutation.SetAffiliateAction(v)
	return _c
}

// SetNillableAffiliateAction sets the "affiliate_action" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableAffiliateAction(v *string) *RefundTicketCreate {
	if v != nil {
		_c.SetAffiliateAction(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *RefundTicketCreate) SetReviewedAt(v time.Time) *RefundTicketCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableReviewedAt(v *time.Time) *RefundTicketCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *RefundTicketCreate) SetCompletedAt(v time.Time) *RefundTicketCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableCompletedAt(v *time.Time) *RefundTicketCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RefundTicketCreate) SetCreatedAt(v time.Time) *RefundTicketCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableCreatedAt(v *time.Time) *RefundTicketCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RefundTicketCreate) SetUpdatedAt(v time.Time) *RefundTicketCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableUpdatedAt(v *time.Time) *RefundTicketCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RefundTicketCreate) SetID(v string) *RefundTicketCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RefundTicketCreate) SetNillableID(v *string) *RefundTicketCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RefundTicketMutation object of the builder.
func (_c *RefundTicketCreate) Mutation() *RefundTicketMutation {
	return _c.mutation
}

// Save creates the RefundTicket in the database.
func (_c *RefundTicketCreate) Save(ctx context.Context) (*RefundTicket, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RefundTicketCreate) SaveX(ctx context.Context) *RefundTicket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefundTicketCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefundTicketCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RefundTicketCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := refundticket.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Comment(); !ok {
		v := refundticket.DefaultComment
		_c.mutation.SetComment(v)
	}
	if _, ok := _c.mutation.ReviewNote(); !ok {
		v := refundticket.DefaultReviewNote
		_c.mutation.SetReviewNote(v)
	}
	if _, ok := _c.mutation.AffiliateAction(); !ok {
		v := refundticket.DefaultAffiliateAction
		_c.mutation.SetAffiliateAction(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := refundticket.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := refundticket.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := refundticket.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RefundTicketCreate) check() error {
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "RefundTicket.order_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RefundTicket.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RefundTicket.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := refundticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RefundTicket.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "RefundTicket.comment"`)}
	}
	if _, ok := _c.mutation.ReviewNote(); !ok {
		return &ValidationError{Name: "review_note", err: errors.New(`ent: missing required field "RefundTicket.review_note"`)}
	}
	if _, ok := _c.mutation.AffiliateAction(); !ok {
		return &ValidationError{Name: "affiliate_action", err: errors.New(`ent: missing required field "RefundTicket.affiliate_action"`)}
	}
	if v, ok := _c.mutation.AffiliateAction(); ok {
		if err := refundticket.AffiliateActionValidator(v); err != nil {
			return &ValidationError{Name: "affiliate_action", err: fmt.Errorf(`ent: validator failed for field "RefundTicket.affiliate_action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RefundTicket.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RefundTicket.updated_at"`)}
	}
	return nil
}

func (_c *RefundTicketCreate) sqlSave(ctx context.Context) (*RefundTicket, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RefundTicket.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RefundTicketCreate) createSpec() (*RefundTicket, *sqlgraph.CreateSpec) {
	var (
		_node = &RefundTicket{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(refundticket.Table, sqlgraph.NewFieldSpec(refundticket.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(refundticket.FieldOrderID, field.TypeString, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(refundticket.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RefundID(); ok {
		_spec.SetField(refundticket.FieldRefundID, field.TypeString, value)
		_node.RefundID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(refundticket.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(refundticket.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.ApprovedPrincipalAmount(); ok {
		_spec.SetField(refundticket.FieldApprovedPrincipalAmount, field.TypeFloat64, value)
		_node.ApprovedPrincipalAmount = &value
	}
	if value, ok := _c.mutation.ReviewerID(); ok {
		_spec.SetField(refundticket.FieldReviewerID, field.TypeString, value)
		_node.ReviewerID = &value
	}
	if value, ok := _c.mutation.ReviewNote(); ok {
		_spec.SetField(refundticket.FieldReviewNote, field.TypeString, value)
		_node.ReviewNote = value
	}
	if value, ok := _c.mutation.AffiliateAction(); ok {
		_spec.SetField(refundticket.FieldAffiliateAction, field.TypeString, value)
		_node.AffiliateAction = value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(refundticket.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(refundticket.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(refundticket.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(refundticket.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RefundTicket.Create().
//		SetOrderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RefundTicketUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *RefundTicketCreate) OnConflict(opts ...sql.ConflictOption) *RefundTicketUpsertOne {
	_c.conflict = opts
	return &RefundTicketUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RefundTicket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RefundTicketCreate) OnConflictColumns(columns ...string) *RefundTicketUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RefundTicketUpsertOne{
		create: _c,
	}
}

type (
	// RefundTicketUpsertOne is the builder for "upsert"-ing
	//  one RefundTicket node.
	RefundTicketUpsertOne struct {
		create *RefundTicketCreate
	}

	// RefundTicketUpsert is the "OnConflict" setter.
	RefundTicketUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderID sets the "order_id" field.
func (u *RefundTicketUpsert) SetOrderID(v string) *RefundTicketUpsert {
	u.Set(refundticket.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateOrderID() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldOrderID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RefundTicketUpsert) SetUserID(v string) *RefundTicketUpsert {
	u.Set(refundticket.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateUserID() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldUserID)
	return u
}

// SetRefundID sets the "refund_id" field.
func (u *RefundTicketUpsert) SetRefundID(v string) *RefundTicketUpsert {
	u.Set(refundticket.FieldRefundID, v)
	return u
}

// UpdateRefundID sets the "refund_id" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateRefundID() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldRefundID)
	return u
}

// ClearRefundID clears the value of the "refund_id" field.
func (u *RefundTicketUpsert) ClearRefundID() *RefundTicketUpsert {
	u.SetNull(refundticket.FieldRefundID)
	return u
}

// SetStatus sets the "status" field.
func (u *RefundTicketUpsert) SetStatus(v string) *RefundTicketUpsert {
	u.Set(refundticket.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateStatus() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldStatus)
	return u
}

// SetComment sets the "comment" field.
func (u *RefundTicketUpsert) SetComment(v string) *RefundTicketUpsert {
	u.Set(refundticket.FieldComment, v)
	return u
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateComment() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldComment)
	return u
}

// SetApprovedPrincipalAmount sets the "approved_principal_amount" field.
func (u *RefundTicketUpsert) SetApprovedPrincipalAmount(v float64) *RefundTicketUpsert {
	u.Set(refundticket.FieldApprovedPrincipalAmount, v)
	return u
}

// UpdateApprovedPrincipalAmount sets the "approved_principal_amount" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateApprovedPrincipalAmount() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldApprovedPrincipalAmount)
	return u
}

// AddApprovedPrincipalAmount adds v to the "approved_principal_amount" field.
func (u *RefundTicketUpsert) AddApprovedPrincipalAmount(v float64) *RefundTicketUpsert {
	u.Add(refundticket.FieldApprovedPrincipalAmount, v)
	return u
}

// ClearApprovedPrincipalAmount clears the value of the "approved_principal_amount" field.
func (u *RefundTicketUpsert) ClearApprovedPrincipalAmount() *RefundTicketUpsert {
	u.SetNull(refundticket.FieldApprovedPrincipalAmount)
	return u
}

// SetReviewerID sets the "reviewer_id" field.
func (u *RefundTicketUpsert) SetReviewerID(v string) *RefundTicketUpsert {
	u.Set(refundticket.FieldReviewerID, v)
	return u
}

// UpdateReviewerID sets the "reviewer_id" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateReviewerID() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldReviewerID)
	return u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (u *RefundTicketUpsert) ClearReviewerID() *RefundTicketUpsert {
	u.SetNull(refundticket.FieldReviewerID)
	return u
}

// SetReviewNote sets the "review_note" field.
func (u *RefundTicketUpsert) SetReviewNote(v string) *RefundTicketUpsert {
	u.Set(refundticket.FieldReviewNote, v)
	return u
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateReviewNote() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldReviewNote)
	return u
}

// SetAffiliateAction sets the "affiliate_action" field.
func (u *RefundTicketUpsert) SetAffiliateAction(v string) *RefundTicketUpsert {
	u.Set(refundticket.FieldAffiliateAction, v)
	return u
}

// UpdateAffiliateAction sets the "affiliate_action" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateAffiliateAction() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldAffiliateAction)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *RefundTicketUpsert) SetReviewedAt(v time.Time) *RefundTicketUpsert {
	u.Set(refundticket.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateReviewedAt() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *RefundTicketUpsert) ClearReviewedAt() *RefundTicketUpsert {
	u.SetNull(refundticket.FieldReviewedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *RefundTicketUpsert) SetCompletedAt(v time.Time) *RefundTicketUpsert {
	u.Set(refundticket.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateCompletedAt() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RefundTicketUpsert) ClearCompletedAt() *RefundTicketUpsert {
	u.SetNull(refundticket.FieldCompletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RefundTicketUpsert) SetUpdatedAt(v time.Time) *RefundTicketUpsert {
	u.Set(refundticket.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RefundTicketUpsert) UpdateUpdatedAt() *RefundTicketUpsert {
	u.SetExcluded(refundticket.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RefundTicket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(refundticket.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RefundTicketUpsertOne) UpdateNewValues() *RefundTicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(refundticket.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(refundticket.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RefundTicket.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RefundTicketUpsertOne) Ignore() *RefundTicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RefundTicketUpsertOne) DoNothing() *RefundTicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RefundTicketCreate.OnConflict
// documentation for more info.
func (u *RefundTicketUpsertOne) Update(set func(*RefundTicketUpsert)) *RefundTicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RefundTicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *RefundTicketUpsertOne) SetOrderID(v string) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateOrderID() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateOrderID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RefundTicketUpsertOne) SetUserID(v string) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateUserID() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateUserID()
	})
}

// SetRefundID sets the "refund_id" field.
func (u *RefundTicketUpsertOne) SetRefundID(v string) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetRefundID(v)
	})
}

// UpdateRefundID sets the "refund_id" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateRefundID() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateRefundID()
	})
}

// ClearRefundID clears the value of the "refund_id" field.
func (u *RefundTicketUpsertOne) ClearRefundID() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearRefundID()
	})
}

// SetStatus sets the "status" field.
func (u *RefundTicketUpsertOne) SetStatus(v string) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateStatus() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateStatus()
	})
}

// SetComment sets the "comment" field.
func (u *RefundTicketUpsertOne) SetComment(v string) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetComment(v)
	})
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateComment() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateComment()
	})
}

// SetApprovedPrincipalAmount sets the "approved_principal_amount" field.
func (u *RefundTicketUpsertOne) SetApprovedPrincipalAmount(v float64) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetApprovedPrincipalAmount(v)
	})
}

// AddApprovedPrincipalAmount adds v to the "approved_principal_amount" field.
func (u *RefundTicketUpsertOne) AddApprovedPrincipalAmount(v float64) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.AddApprovedPrincipalAmount(v)
	})
}

// UpdateApprovedPrincipalAmount sets the "approved_principal_amount" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateApprovedPrincipalAmount() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateApprovedPrincipalAmount()
	})
}

// ClearApprovedPrincipalAmount clears the value of the "approved_principal_amount" field.
func (u *RefundTicketUpsertOne) ClearApprovedPrincipalAmount() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearApprovedPrincipalAmount()
	})
}

// SetReviewerID sets the "reviewer_id" field.
func (u *RefundTicketUpsertOne) SetReviewerID(v string) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetReviewerID(v)
	})
}

// UpdateReviewerID sets the "reviewer_id" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateReviewerID() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateReviewerID()
	})
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (u *RefundTicketUpsertOne) ClearReviewerID() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearReviewerID()
	})
}

// SetReviewNote sets the "review_note" field.
func (u *RefundTicketUpsertOne) SetReviewNote(v string) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetReviewNote(v)
	})
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateReviewNote() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateReviewNote()
	})
}

// SetAffiliateAction sets the "affiliate_action" field.
func (u *RefundTicketUpsertOne) SetAffiliateAction(v string) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetAffiliateAction(v)
	})
}

// UpdateAffiliateAction sets the "affiliate_action" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateAffiliateAction() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateAffiliateAction()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *RefundTicketUpsertOne) SetReviewedAt(v time.Time) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateReviewedAt() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *RefundTicketUpsertOne) ClearReviewedAt() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearReviewedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *RefundTicketUpsertOne) SetCompletedAt(v time.Time) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateCompletedAt() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RefundTicketUpsertOne) ClearCompletedAt() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RefundTicketUpsertOne) SetUpdatedAt(v time.Time) *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RefundTicketUpsertOne) UpdateUpdatedAt() *RefundTicketUpsertOne {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RefundTicketUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RefundTicketCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RefundTicketUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RefundTicketUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RefundTicketUpsertOne.ID is not supported by MySQL driver. Use RefundTicketUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RefundTicketUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RefundTicketCreateBulk is the builder for creating many RefundTicket entities in bulk.
type RefundTicketCreateBulk struct {
	config
	err      error
	builders []*RefundTicketCreate
	conflict []sql.ConflictOption
}

// Save creates the RefundTicket entities in the database.
func (_c *RefundTicketCreateBulk) Save(ctx context.Context) ([]*RefundTicket, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RefundTicket, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefundTicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RefundTicketCreateBulk) SaveX(ctx context.Context) []*RefundTicket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RefundTicketCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RefundTicketCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RefundTicket.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RefundTicketUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *RefundTicketCreateBulk) OnConflict(opts ...sql.ConflictOption) *RefundTicketUpsertBulk {
	_c.conflict = opts
	return &RefundTicketUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RefundTicket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RefundTicketCreateBulk) OnConflictColumns(columns ...string) *RefundTicketUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RefundTicketUpsertBulk{
		create: _c,
	}
}

// RefundTicketUpsertBulk is the builder for "upsert"-ing
// a bulk of RefundTicket nodes.
type RefundTicketUpsertBulk struct {
	create *RefundTicketCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RefundTicket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(refundticket.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RefundTicketUpsertBulk) UpdateNewValues() *RefundTicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(refundticket.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(refundticket.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RefundTicket.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RefundTicketUpsertBulk) Ignore() *RefundTicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RefundTicketUpsertBulk) DoNothing() *RefundTicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RefundTicketCreateBulk.OnConflict
// documentation for more info.
func (u *RefundTicketUpsertBulk) Update(set func(*RefundTicketUpsert)) *RefundTicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RefundTicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *RefundTicketUpsertBulk) SetOrderID(v string) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateOrderID() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateOrderID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RefundTicketUpsertBulk) SetUserID(v string) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateUserID() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateUserID()
	})
}

// SetRefundID sets the "refund_id" field.
func (u *RefundTicketUpsertBulk) SetRefundID(v string) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetRefundID(v)
	})
}

// UpdateRefundID sets the "refund_id" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateRefundID() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateRefundID()
	})
}

// ClearRefundID clears the value of the "refund_id" field.
func (u *RefundTicketUpsertBulk) ClearRefundID() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearRefundID()
	})
}

// SetStatus sets the "status" field.
func (u *RefundTicketUpsertBulk) SetStatus(v string) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateStatus() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateStatus()
	})
}

// SetComment sets the "comment" field.
func (u *RefundTicketUpsertBulk) SetComment(v string) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetComment(v)
	})
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateComment() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateComment()
	})
}

// SetApprovedPrincipalAmount sets the "approved_principal_amount" field.
func (u *RefundTicketUpsertBulk) SetApprovedPrincipalAmount(v float64) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetApprovedPrincipalAmount(v)
	})
}

// AddApprovedPrincipalAmount adds v to the "approved_principal_amount" field.
func (u *RefundTicketUpsertBulk) AddApprovedPrincipalAmount(v float64) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.AddApprovedPrincipalAmount(v)
	})
}

// UpdateApprovedPrincipalAmount sets the "approved_principal_amount" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateApprovedPrincipalAmount() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateApprovedPrincipalAmount()
	})
}

// ClearApprovedPrincipalAmount clears the value of the "approved_principal_amount" field.
func (u *RefundTicketUpsertBulk) ClearApprovedPrincipalAmount() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearApprovedPrincipalAmount()
	})
}

// SetReviewerID sets the "reviewer_id" field.
func (u *RefundTicketUpsertBulk) SetReviewerID(v string) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetReviewerID(v)
	})
}

// UpdateReviewerID sets the "reviewer_id" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateReviewerID() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateReviewerID()
	})
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (u *RefundTicketUpsertBulk) ClearReviewerID() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearReviewerID()
	})
}

// SetReviewNote sets the "review_note" field.
func (u *RefundTicketUpsertBulk) SetReviewNote(v string) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetReviewNote(v)
	})
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateReviewNote() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateReviewNote()
	})
}

// SetAffiliateAction sets the "affiliate_action" field.
func (u *RefundTicketUpsertBulk) SetAffiliateAction(v string) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetAffiliateAction(v)
	})
}

// UpdateAffiliateAction sets the "affiliate_action" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateAffiliateAction() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateAffiliateAction()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *RefundTicketUpsertBulk) SetReviewedAt(v time.Time) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateReviewedAt() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *RefundTicketUpsertBulk) ClearReviewedAt() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearReviewedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *RefundTicketUpsertBulk) SetCompletedAt(v time.Time) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateCompletedAt() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RefundTicketUpsertBulk) ClearCompletedAt() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RefundTicketUpsertBulk) SetUpdatedAt(v time.Time) *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RefundTicketUpsertBulk) UpdateUpdatedAt() *RefundTicketUpsertBulk {
	return u.Update(func(s *RefundTicketUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RefundTicketUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RefundTicketCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RefundTicketCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RefundTicketUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
