// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AsukaCC/EasySub2api/ent/predicate"
	"github.com/AsukaCC/EasySub2api/ent/supportticket"
)

// SupportTicketUpdate is the builder for updating SupportTicket entities.
type SupportTicketUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdate) Where(ps ...predicate.SupportTicket) *SupportTicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdate) SetUserID(v string) *SupportTicketUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableUserID(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportTicketUpdate) SetCategory(v string) *SupportTicketUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableCategory(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdate) SetStatus(v string) *SupportTicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableStatus(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *SupportTicketUpdate) SetOrigin(v string) *SupportTicketUpdate {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableOrigin(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportTicketUpdate) SetTitle(v string) *SupportTicketUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableTitle(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SupportTicketUpdate) SetAPIKeyID(v string) *SupportTicketUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableAPIKeyID(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *SupportTicketUpdate) ClearAPIKeyID() *SupportTicketUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (_u *SupportTicketUpdate) SetAPIKeyNameSnapshot(v string) *SupportTicketUpdate {
	_u.mutation.SetAPIKeyNameSnapshot(v)
	return _u
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableAPIKeyNameSnapshot(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetAPIKeyNameSnapshot(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SupportTicketUpdate) SetGroupID(v string) *SupportTicketUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableGroupID(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *SupportTicketUpdate) ClearGroupID() *SupportTicketUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetGroupNameSnapshot sets the "group_name_snapshot" field.
func (_u *SupportTicketUpdate) SetGroupNameSnapshot(v string) *SupportTicketUpdate {
	_u.mutation.SetGroupNameSnapshot(v)
	return _u
}

// SetNillableGroupNameSnapshot sets the "group_name_snapshot" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableGroupNameSnapshot(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetGroupNameSnapshot(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SupportTicketUpdate) SetOrderID(v string) *SupportTicketUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableOrderID(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *SupportTicketUpdate) ClearOrderID() *SupportTicketUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// SetRefundID sets the "refund_id" field.
func (_u *SupportTicketUpdate) SetRefundID(v string) *SupportTicketUpdate {
	_u.mutation.SetRefundID(v)
	return _u
}

// SetNillableRefundID sets the "refund_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableRefundID(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetRefundID(*v)
	}
	return _u
}

// ClearRefundID clears the value of the "refund_id" field.
func (_u *SupportTicketUpdate) ClearRefundID() *SupportTicketUpdate {
	_u.mutation.ClearRefundID()
	return _u
}

// SetRefundDecision sets the "refund_decision" field.
func (_u *SupportTicketUpdate) SetRefundDecision(v string) *SupportTicketUpdate {
	_u.mutation.SetRefundDecision(v)
	return _u
}

// SetNillableRefundDecision sets the "refund_decision" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableRefundDecision(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetRefundDecision(*v)
	}
	return _u
}

// SetApprovedPrincipalAmount sets the "approved_principal_amount" field.
func (_u *SupportTicketUpdate) SetApprovedPrincipalAmount(v float64) *SupportTicketUpdate {
	_u.mutation.ResetApprovedPrincipalAmount()
	_u.mutation.SetApprovedPrincipalAmount(v)
	return _u
}

// SetNillableApprovedPrincipalAmount sets the "approved_principal_amount" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableApprovedPrincipalAmount(v *float64) *SupportTicketUpdate {
	if v != nil {
		_u.SetApprovedPrincipalAmount(*v)
	}
	return _u
}

// AddApprovedPrincipalAmount adds value to the "approved_principal_amount" field.
func (_u *SupportTicketUpdate) AddApprovedPrincipalAmount(v float64) *SupportTicketUpdate {
	_u.mutation.AddApprovedPrincipalAmount(v)
	return _u
}

// ClearApprovedPrincipalAmount clears the value of the "approved_principal_amount" field.
func (_u *SupportTicketUpdate) ClearApprovedPrincipalAmount() *SupportTicketUpdate {
	_u.mutation.ClearApprovedPrincipalAmount()
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *SupportTicketUpdate) SetReviewerID(v string) *SupportTicketUpdate {
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableReviewerID(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (_u *SupportTicketUpdate) ClearReviewerID() *SupportTicketUpdate {
	_u.mutation.ClearReviewerID()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SupportTicketUpdate) SetReviewedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableReviewedAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SupportTicketUpdate) ClearReviewedAt() *SupportTicketUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReopenCount sets the "reopen_count" field.
func (_u *SupportTicketUpdate) SetReopenCount(v int) *SupportTicketUpdate {
	_u.mutation.ResetReopenCount()
	_u.mutation.SetReopenCount(v)
	return _u
}

// SetNillableReopenCount sets the "reopen_count" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableReopenCount(v *int) *SupportTicketUpdate {
	if v != nil {
		_u.SetReopenCount(*v)
	}
	return _u
}

// AddReopenCount adds value to the "reopen_count" field.
func (_u *SupportTicketUpdate) AddReopenCount(v int) *SupportTicketUpdate {
	_u.mutation.AddReopenCount(v)
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *SupportTicketUpdate) SetResolvedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableResolvedAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *SupportTicketUpdate) ClearResolvedAt() *SupportTicketUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SupportTicketUpdate) SetClosedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SupportTicketUpdate) ClearClosedAt() *SupportTicketUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetLastUserActivityAt sets the "last_user_activity_at" field.
func (_u *SupportTicketUpdate) SetLastUserActivityAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetLastUserActivityAt(v)
	return _u
}

// SetNillableLastUserActivityAt sets the "last_user_activity_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableLastUserActivityAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetLastUserActivityAt(*v)
	}
	return _u
}

// ClearLastUserActivityAt clears the value of the "last_user_activity_at" field.
func (_u *SupportTicketUpdate) ClearLastUserActivityAt() *SupportTicketUpdate {
	_u.mutation.ClearLastUserActivityAt()
	return _u
}

// SetLastAdminActivityAt sets the "last_admin_activity_at" field.
func (_u *SupportTicketUpdate) SetLastAdminActivityAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetLastAdminActivityAt(v)
	return _u
}

// SetNillableLastAdminActivityAt sets the "last_admin_activity_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableLastAdminActivityAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetLastAdminActivityAt(*v)
	}
	return _u
}

// ClearLastAdminActivityAt clears the value of the "last_admin_activity_at" field.
func (_u *SupportTicketUpdate) ClearLastAdminActivityAt() *SupportTicketUpdate {
	_u.mutation.ClearLastAdminActivityAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdate) SetUpdatedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdate) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdate) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Origin(); ok {
		if err := supportticket.OriginValidator(v); err != nil {
			return &ValidationError{Name: "origin", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.origin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := supportticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyNameSnapshot(); ok {
		if err := supportticket.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.api_key_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupNameSnapshot(); ok {
		if err := supportticket.GroupNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "group_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.group_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundDecision(); ok {
		if err := supportticket.RefundDecisionValidator(v); err != nil {
			return &ValidationError{Name: "refund_decision", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.refund_decision": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(supportticket.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(supportticket.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportticket.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(supportticket.FieldAPIKeyID, field.TypeString, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(supportticket.FieldAPIKeyID, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(supportticket.FieldAPIKeyNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(supportticket.FieldGroupID, field.TypeString, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(supportticket.FieldGroupID, field.TypeString)
	}
	if value, ok := _u.mutation.GroupNameSnapshot(); ok {
		_spec.SetField(supportticket.FieldGroupNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(supportticket.FieldOrderID, field.TypeString, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(supportticket.FieldOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.RefundID(); ok {
		_spec.SetField(supportticket.FieldRefundID, field.TypeString, value)
	}
	if _u.mutation.RefundIDCleared() {
		_spec.ClearField(supportticket.FieldRefundID, field.TypeString)
	}
	if value, ok := _u.mutation.RefundDecision(); ok {
		_spec.SetField(supportticket.FieldRefundDecision, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedPrincipalAmount(); ok {
		_spec.SetField(supportticket.FieldApprovedPrincipalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedApprovedPrincipalAmount(); ok {
		_spec.AddField(supportticket.FieldApprovedPrincipalAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ApprovedPrincipalAmountCleared() {
		_spec.ClearField(supportticket.FieldApprovedPrincipalAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(supportticket.FieldReviewerID, field.TypeString, value)
	}
	if _u.mutation.ReviewerIDCleared() {
		_spec.ClearField(supportticket.FieldReviewerID, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(supportticket.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(supportticket.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReopenCount(); ok {
		_spec.SetField(supportticket.FieldReopenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReopenCount(); ok {
		_spec.AddField(supportticket.FieldReopenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(supportticket.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(supportticket.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(supportticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(supportticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUserActivityAt(); ok {
		_spec.SetField(supportticket.FieldLastUserActivityAt, field.TypeTime, value)
	}
	if _u.mutation.LastUserActivityAtCleared() {
		_spec.ClearField(supportticket.FieldLastUserActivityAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAdminActivityAt(); ok {
		_spec.SetField(supportticket.FieldLastAdminActivityAt, field.TypeTime, value)
	}
	if _u.mutation.LastAdminActivityAtCleared() {
		_spec.ClearField(supportticket.FieldLastAdminActivityAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketUpdateOne is the builder for updating a single SupportTicket entity.
type SupportTicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMutation
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdateOne) SetUserID(v string) *SupportTicketUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableUserID(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportTicketUpdateOne) SetCategory(v string) *SupportTicketUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableCategory(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdateOne) SetStatus(v string) *SupportTicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableStatus(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOrigin sets the "origin" field.
func (_u *SupportTicketUpdateOne) SetOrigin(v string) *SupportTicketUpdateOne {
	_u.mutation.SetOrigin(v)
	return _u
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableOrigin(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetOrigin(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportTicketUpdateOne) SetTitle(v string) *SupportTicketUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableTitle(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SupportTicketUpdateOne) SetAPIKeyID(v string) *SupportTicketUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableAPIKeyID(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *SupportTicketUpdateOne) ClearAPIKeyID() *SupportTicketUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (_u *SupportTicketUpdateOne) SetAPIKeyNameSnapshot(v string) *SupportTicketUpdateOne {
	_u.mutation.SetAPIKeyNameSnapshot(v)
	return _u
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableAPIKeyNameSnapshot(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetAPIKeyNameSnapshot(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SupportTicketUpdateOne) SetGroupID(v string) *SupportTicketUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableGroupID(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *SupportTicketUpdateOne) ClearGroupID() *SupportTicketUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetGroupNameSnapshot sets the "group_name_snapshot" field.
func (_u *SupportTicketUpdateOne) SetGroupNameSnapshot(v string) *SupportTicketUpdateOne {
	_u.mutation.SetGroupNameSnapshot(v)
	return _u
}

// SetNillableGroupNameSnapshot sets the "group_name_snapshot" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableGroupNameSnapshot(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetGroupNameSnapshot(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SupportTicketUpdateOne) SetOrderID(v string) *SupportTicketUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableOrderID(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *SupportTicketUpdateOne) ClearOrderID() *SupportTicketUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// SetRefundID sets the "refund_id" field.
func (_u *SupportTicketUpdateOne) SetRefundID(v string) *SupportTicketUpdateOne {
	_u.mutation.SetRefundID(v)
	return _u
}

// SetNillableRefundID sets the "refund_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableRefundID(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetRefundID(*v)
	}
	return _u
}

// ClearRefundID clears the value of the "refund_id" field.
func (_u *SupportTicketUpdateOne) ClearRefundID() *SupportTicketUpdateOne {
	_u.mutation.ClearRefundID()
	return _u
}

// SetRefundDecision sets the "refund_decision" field.
func (_u *SupportTicketUpdateOne) SetRefundDecision(v string) *SupportTicketUpdateOne {
	_u.mutation.SetRefundDecision(v)
	return _u
}

// SetNillableRefundDecision sets the "refund_decision" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableRefundDecision(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetRefundDecision(*v)
	}
	return _u
}

// SetApprovedPrincipalAmount sets the "approved_principal_amount" field.
func (_u *SupportTicketUpdateOne) SetApprovedPrincipalAmount(v float64) *SupportTicketUpdateOne {
	_u.mutation.ResetApprovedPrincipalAmount()
	_u.mutation.SetApprovedPrincipalAmount(v)
	return _u
}

// SetNillableApprovedPrincipalAmount sets the "approved_principal_amount" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableApprovedPrincipalAmount(v *float64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetApprovedPrincipalAmount(*v)
	}
	return _u
}

// AddApprovedPrincipalAmount adds value to the "approved_principal_amount" field.
func (_u *SupportTicketUpdateOne) AddApprovedPrincipalAmount(v float64) *SupportTicketUpdateOne {
	_u.mutation.AddApprovedPrincipalAmount(v)
	return _u
}

// ClearApprovedPrincipalAmount clears the value of the "approved_principal_amount" field.
func (_u *SupportTicketUpdateOne) ClearApprovedPrincipalAmount() *SupportTicketUpdateOne {
	_u.mutation.ClearApprovedPrincipalAmount()
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *SupportTicketUpdateOne) SetReviewerID(v string) *SupportTicketUpdateOne {
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableReviewerID(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (_u *SupportTicketUpdateOne) ClearReviewerID() *SupportTicketUpdateOne {
	_u.mutation.ClearReviewerID()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SupportTicketUpdateOne) SetReviewedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableReviewedAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SupportTicketUpdateOne) ClearReviewedAt() *SupportTicketUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReopenCount sets the "reopen_count" field.
func (_u *SupportTicketUpdateOne) SetReopenCount(v int) *SupportTicketUpdateOne {
	_u.mutation.ResetReopenCount()
	_u.mutation.SetReopenCount(v)
	return _u
}

// SetNillableReopenCount sets the "reopen_count" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableReopenCount(v *int) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetReopenCount(*v)
	}
	return _u
}

// AddReopenCount adds value to the "reopen_count" field.
func (_u *SupportTicketUpdateOne) AddReopenCount(v int) *SupportTicketUpdateOne {
	_u.mutation.AddReopenCount(v)
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *SupportTicketUpdateOne) SetResolvedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableResolvedAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *SupportTicketUpdateOne) ClearResolvedAt() *SupportTicketUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SupportTicketUpdateOne) SetClosedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SupportTicketUpdateOne) ClearClosedAt() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetLastUserActivityAt sets the "last_user_activity_at" field.
func (_u *SupportTicketUpdateOne) SetLastUserActivityAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetLastUserActivityAt(v)
	return _u
}

// SetNillableLastUserActivityAt sets the "last_user_activity_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableLastUserActivityAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetLastUserActivityAt(*v)
	}
	return _u
}

// ClearLastUserActivityAt clears the value of the "last_user_activity_at" field.
func (_u *SupportTicketUpdateOne) ClearLastUserActivityAt() *SupportTicketUpdateOne {
	_u.mutation.ClearLastUserActivityAt()
	return _u
}

// SetLastAdminActivityAt sets the "last_admin_activity_at" field.
func (_u *SupportTicketUpdateOne) SetLastAdminActivityAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetLastAdminActivityAt(v)
	return _u
}

// SetNillableLastAdminActivityAt sets the "last_admin_activity_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableLastAdminActivityAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetLastAdminActivityAt(*v)
	}
	return _u
}

// ClearLastAdminActivityAt clears the value of the "last_admin_activity_at" field.
func (_u *SupportTicketUpdateOne) ClearLastAdminActivityAt() *SupportTicketUpdateOne {
	_u.mutation.ClearLastAdminActivityAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdateOne) SetUpdatedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdateOne) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdateOne) Where(ps ...predicate.SupportTicket) *SupportTicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketUpdateOne) Select(field string, fields ...string) *SupportTicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicket entity.
func (_u *SupportTicketUpdateOne) Save(ctx context.Context) (*SupportTicket, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) SaveX(ctx context.Context) *SupportTicket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdateOne) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Origin(); ok {
		if err := supportticket.OriginValidator(v); err != nil {
			return &ValidationError{Name: "origin", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.origin": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := supportticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyNameSnapshot(); ok {
		if err := supportticket.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.api_key_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupNameSnapshot(); ok {
		if err := supportticket.GroupNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "group_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.group_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundDecision(); ok {
		if err := supportticket.RefundDecisionValidator(v); err != nil {
			return &ValidationError{Name: "refund_decision", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.refund_decision": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticket.FieldID)
		for _, f := range fields {
			if !supportticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(supportticket.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Origin(); ok {
		_spec.SetField(supportticket.FieldOrigin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportticket.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(supportticket.FieldAPIKeyID, field.TypeString, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(supportticket.FieldAPIKeyID, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(supportticket.FieldAPIKeyNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(supportticket.FieldGroupID, field.TypeString, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(supportticket.FieldGroupID, field.TypeString)
	}
	if value, ok := _u.mutation.GroupNameSnapshot(); ok {
		_spec.SetField(supportticket.FieldGroupNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(supportticket.FieldOrderID, field.TypeString, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(supportticket.FieldOrderID, field.TypeString)
	}
	if value, ok := _u.mutation.RefundID(); ok {
		_spec.SetField(supportticket.FieldRefundID, field.TypeString, value)
	}
	if _u.mutation.RefundIDCleared() {
		_spec.ClearField(supportticket.FieldRefundID, field.TypeString)
	}
	if value, ok := _u.mutation.RefundDecision(); ok {
		_spec.SetField(supportticket.FieldRefundDecision, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedPrincipalAmount(); ok {
		_spec.SetField(supportticket.FieldApprovedPrincipalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedApprovedPrincipalAmount(); ok {
		_spec.AddField(supportticket.FieldApprovedPrincipalAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ApprovedPrincipalAmountCleared() {
		_spec.ClearField(supportticket.FieldApprovedPrincipalAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(supportticket.FieldReviewerID, field.TypeString, value)
	}
	if _u.mutation.ReviewerIDCleared() {
		_spec.ClearField(supportticket.FieldReviewerID, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(supportticket.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(supportticket.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReopenCount(); ok {
		_spec.SetField(supportticket.FieldReopenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReopenCount(); ok {
		_spec.AddField(supportticket.FieldReopenCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(supportticket.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(supportticket.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(supportticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(supportticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUserActivityAt(); ok {
		_spec.SetField(supportticket.FieldLastUserActivityAt, field.TypeTime, value)
	}
	if _u.mutation.LastUserActivityAtCleared() {
		_spec.ClearField(supportticket.FieldLastUserActivityAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAdminActivityAt(); ok {
		_spec.SetField(supportticket.FieldLastAdminActivityAt, field.TypeTime, value)
	}
	if _u.mutation.LastAdminActivityAtCleared() {
		_spec.ClearField(supportticket.FieldLastAdminActivityAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SupportTicket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
