// Code generated by ent, DO NOT EDIT.

package identityadoptiondecision

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/AsukaCC/EasySub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldUpdatedAt, v))
}

// PendingAuthSessionID applies equality check predicate on the "pending_auth_session_id" field. It's identical to PendingAuthSessionIDEQ.
func PendingAuthSessionID(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldPendingAuthSessionID, v))
}

// IdentityID applies equality check predicate on the "identity_id" field. It's identical to IdentityIDEQ.
func IdentityID(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldIdentityID, v))
}

// AdoptDisplayName applies equality check predicate on the "adopt_display_name" field. It's identical to AdoptDisplayNameEQ.
func AdoptDisplayName(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldAdoptDisplayName, v))
}

// AdoptAvatar applies equality check predicate on the "adopt_avatar" field. It's identical to AdoptAvatarEQ.
func AdoptAvatar(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldAdoptAvatar, v))
}

// DecidedAt applies equality check predicate on the "decided_at" field. It's identical to DecidedAtEQ.
func DecidedAt(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldDecidedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldUpdatedAt, v))
}

// PendingAuthSessionIDEQ applies the EQ predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDEQ(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDNEQ applies the NEQ predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDNEQ(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDIn applies the In predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDIn(vs ...string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldPendingAuthSessionID, vs...))
}

// PendingAuthSessionIDNotIn applies the NotIn predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDNotIn(vs ...string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldPendingAuthSessionID, vs...))
}

// PendingAuthSessionIDGT applies the GT predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDGT(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDGTE applies the GTE predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDGTE(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDLT applies the LT predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDLT(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDLTE applies the LTE predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDLTE(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDContains applies the Contains predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDContains(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldContains(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDHasPrefix applies the HasPrefix predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDHasPrefix(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldHasPrefix(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDHasSuffix applies the HasSuffix predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDHasSuffix(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldHasSuffix(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDEqualFold applies the EqualFold predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDEqualFold(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEqualFold(FieldPendingAuthSessionID, v))
}

// PendingAuthSessionIDContainsFold applies the ContainsFold predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDContainsFold(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldContainsFold(FieldPendingAuthSessionID, v))
}

// IdentityIDEQ applies the EQ predicate on the "identity_id" field.
func IdentityIDEQ(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldIdentityID, v))
}

// IdentityIDNEQ applies the NEQ predicate on the "identity_id" field.
func IdentityIDNEQ(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldIdentityID, v))
}

// IdentityIDIn applies the In predicate on the "identity_id" field.
func IdentityIDIn(vs ...string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldIdentityID, vs...))
}

// IdentityIDNotIn applies the NotIn predicate on the "identity_id" field.
func IdentityIDNotIn(vs ...string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldIdentityID, vs...))
}

// IdentityIDGT applies the GT predicate on the "identity_id" field.
func IdentityIDGT(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldIdentityID, v))
}

// IdentityIDGTE applies the GTE predicate on the "identity_id" field.
func IdentityIDGTE(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldIdentityID, v))
}

// IdentityIDLT applies the LT predicate on the "identity_id" field.
func IdentityIDLT(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldIdentityID, v))
}

// IdentityIDLTE applies the LTE predicate on the "identity_id" field.
func IdentityIDLTE(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldIdentityID, v))
}

// IdentityIDContains applies the Contains predicate on the "identity_id" field.
func IdentityIDContains(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldContains(FieldIdentityID, v))
}

// IdentityIDHasPrefix applies the HasPrefix predicate on the "identity_id" field.
func IdentityIDHasPrefix(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldHasPrefix(FieldIdentityID, v))
}

// IdentityIDHasSuffix applies the HasSuffix predicate on the "identity_id" field.
func IdentityIDHasSuffix(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldHasSuffix(FieldIdentityID, v))
}

// IdentityIDIsNil applies the IsNil predicate on the "identity_id" field.
func IdentityIDIsNil() predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIsNull(FieldIdentityID))
}

// IdentityIDNotNil applies the NotNil predicate on the "identity_id" field.
func IdentityIDNotNil() predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotNull(FieldIdentityID))
}

// IdentityIDEqualFold applies the EqualFold predicate on the "identity_id" field.
func IdentityIDEqualFold(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEqualFold(FieldIdentityID, v))
}

// IdentityIDContainsFold applies the ContainsFold predicate on the "identity_id" field.
func IdentityIDContainsFold(v string) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldContainsFold(FieldIdentityID, v))
}

// AdoptDisplayNameEQ applies the EQ predicate on the "adopt_display_name" field.
func AdoptDisplayNameEQ(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldAdoptDisplayName, v))
}

// AdoptDisplayNameNEQ applies the NEQ predicate on the "adopt_display_name" field.
func AdoptDisplayNameNEQ(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldAdoptDisplayName, v))
}

// AdoptAvatarEQ applies the EQ predicate on the "adopt_avatar" field.
func AdoptAvatarEQ(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldAdoptAvatar, v))
}

// AdoptAvatarNEQ applies the NEQ predicate on the "adopt_avatar" field.
func AdoptAvatarNEQ(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldAdoptAvatar, v))
}

// DecidedAtEQ applies the EQ predicate on the "decided_at" field.
func DecidedAtEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldDecidedAt, v))
}

// DecidedAtNEQ applies the NEQ predicate on the "decided_at" field.
func DecidedAtNEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldDecidedAt, v))
}

// DecidedAtIn applies the In predicate on the "decided_at" field.
func DecidedAtIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldDecidedAt, vs...))
}

// DecidedAtNotIn applies the NotIn predicate on the "decided_at" field.
func DecidedAtNotIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldDecidedAt, vs...))
}

// DecidedAtGT applies the GT predicate on the "decided_at" field.
func DecidedAtGT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldDecidedAt, v))
}

// DecidedAtGTE applies the GTE predicate on the "decided_at" field.
func DecidedAtGTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldDecidedAt, v))
}

// DecidedAtLT applies the LT predicate on the "decided_at" field.
func DecidedAtLT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldDecidedAt, v))
}

// DecidedAtLTE applies the LTE predicate on the "decided_at" field.
func DecidedAtLTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldDecidedAt, v))
}

// HasPendingAuthSession applies the HasEdge predicate on the "pending_auth_session" edge.
func HasPendingAuthSession() predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PendingAuthSessionTable, PendingAuthSessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPendingAuthSessionWith applies the HasEdge predicate on the "pending_auth_session" edge with a given conditions (other predicates).
func HasPendingAuthSessionWith(preds ...predicate.PendingAuthSession) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(func(s *sql.Selector) {
		step := newPendingAuthSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIdentity applies the HasEdge predicate on the "identity" edge.
func HasIdentity() predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IdentityTable, IdentityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIdentityWith applies the HasEdge predicate on the "identity" edge with a given conditions (other predicates).
func HasIdentityWith(preds ...predicate.AuthIdentity) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(func(s *sql.Selector) {
		step := newIdentityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IdentityAdoptionDecision) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IdentityAdoptionDecision) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IdentityAdoptionDecision) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.NotPredicates(p))
}
