// Code generated by ent, DO NOT EDIT.

package accountmodelrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/AsukaCC/EasySub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldDescription, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldPlatform, v))
}

// SubscriptionTier applies equality check predicate on the "subscription_tier" field. It's identical to SubscriptionTierEQ.
func SubscriptionTier(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldSubscriptionTier, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContainsFold(FieldDescription, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContainsFold(FieldPlatform, v))
}

// SubscriptionTierEQ applies the EQ predicate on the "subscription_tier" field.
func SubscriptionTierEQ(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEQ(FieldSubscriptionTier, v))
}

// SubscriptionTierNEQ applies the NEQ predicate on the "subscription_tier" field.
func SubscriptionTierNEQ(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNEQ(FieldSubscriptionTier, v))
}

// SubscriptionTierIn applies the In predicate on the "subscription_tier" field.
func SubscriptionTierIn(vs ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIn(FieldSubscriptionTier, vs...))
}

// SubscriptionTierNotIn applies the NotIn predicate on the "subscription_tier" field.
func SubscriptionTierNotIn(vs ...string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotIn(FieldSubscriptionTier, vs...))
}

// SubscriptionTierGT applies the GT predicate on the "subscription_tier" field.
func SubscriptionTierGT(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGT(FieldSubscriptionTier, v))
}

// SubscriptionTierGTE applies the GTE predicate on the "subscription_tier" field.
func SubscriptionTierGTE(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldGTE(FieldSubscriptionTier, v))
}

// SubscriptionTierLT applies the LT predicate on the "subscription_tier" field.
func SubscriptionTierLT(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLT(FieldSubscriptionTier, v))
}

// SubscriptionTierLTE applies the LTE predicate on the "subscription_tier" field.
func SubscriptionTierLTE(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldLTE(FieldSubscriptionTier, v))
}

// SubscriptionTierContains applies the Contains predicate on the "subscription_tier" field.
func SubscriptionTierContains(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContains(FieldSubscriptionTier, v))
}

// SubscriptionTierHasPrefix applies the HasPrefix predicate on the "subscription_tier" field.
func SubscriptionTierHasPrefix(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldHasPrefix(FieldSubscriptionTier, v))
}

// SubscriptionTierHasSuffix applies the HasSuffix predicate on the "subscription_tier" field.
func SubscriptionTierHasSuffix(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldHasSuffix(FieldSubscriptionTier, v))
}

// SubscriptionTierIsNil applies the IsNil predicate on the "subscription_tier" field.
func SubscriptionTierIsNil() predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldIsNull(FieldSubscriptionTier))
}

// SubscriptionTierNotNil applies the NotNil predicate on the "subscription_tier" field.
func SubscriptionTierNotNil() predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldNotNull(FieldSubscriptionTier))
}

// SubscriptionTierEqualFold applies the EqualFold predicate on the "subscription_tier" field.
func SubscriptionTierEqualFold(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldEqualFold(FieldSubscriptionTier, v))
}

// SubscriptionTierContainsFold applies the ContainsFold predicate on the "subscription_tier" field.
func SubscriptionTierContainsFold(v string) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.FieldContainsFold(FieldSubscriptionTier, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountModelRule) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountModelRule) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountModelRule) predicate.AccountModelRule {
	return predicate.AccountModelRule(sql.NotPredicates(p))
}
