// Code generated by ent, DO NOT EDIT.

package refundticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the refundticket type in the database.
	Label = "refund_ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRefundID holds the string denoting the refund_id field in the database.
	FieldRefundID = "refund_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldApprovedPrincipalAmount holds the string denoting the approved_principal_amount field in the database.
	FieldApprovedPrincipalAmount = "approved_principal_amount"
	// FieldReviewerID holds the string denoting the reviewer_id field in the database.
	FieldReviewerID = "reviewer_id"
	// FieldReviewNote holds the string denoting the review_note field in the database.
	FieldReviewNote = "review_note"
	// FieldAffiliateAction holds the string denoting the affiliate_action field in the database.
	FieldAffiliateAction = "affiliate_action"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewed_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the refundticket in the database.
	Table = "refund_tickets"
)

// Columns holds all SQL columns for refundticket fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldUserID,
	FieldRefundID,
	FieldStatus,
	FieldComment,
	FieldApprovedPrincipalAmount,
	FieldReviewerID,
	FieldReviewNote,
	FieldAffiliateAction,
	FieldReviewedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultComment holds the default value on creation for the "comment" field.
	DefaultComment string
	// DefaultReviewNote holds the default value on creation for the "review_note" field.
	DefaultReviewNote string
	// DefaultAffiliateAction holds the default value on creation for the "affiliate_action" field.
	DefaultAffiliateAction string
	// AffiliateActionValidator is a validator for the "affiliate_action" field. It is called by the builders before save.
	AffiliateActionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the RefundTicket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRefundID orders the results by the refund_id field.
func ByRefundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByApprovedPrincipalAmount orders the results by the approved_principal_amount field.
func ByApprovedPrincipalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedPrincipalAmount, opts...).ToFunc()
}

// ByReviewerID orders the results by the reviewer_id field.
func ByReviewerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewerID, opts...).ToFunc()
}

// ByReviewNote orders the results by the review_note field.
func ByReviewNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewNote, opts...).ToFunc()
}

// ByAffiliateAction orders the results by the affiliate_action field.
func ByAffiliateAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffiliateAction, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
