// Code generated by ent, DO NOT EDIT.

package refundticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/AsukaCC/EasySub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldID, id))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldOrderID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldUserID, v))
}

// RefundID applies equality check predicate on the "refund_id" field. It's identical to RefundIDEQ.
func RefundID(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldRefundID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldStatus, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldComment, v))
}

// ApprovedPrincipalAmount applies equality check predicate on the "approved_principal_amount" field. It's identical to ApprovedPrincipalAmountEQ.
func ApprovedPrincipalAmount(v float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldApprovedPrincipalAmount, v))
}

// ReviewerID applies equality check predicate on the "reviewer_id" field. It's identical to ReviewerIDEQ.
func ReviewerID(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldReviewerID, v))
}

// ReviewNote applies equality check predicate on the "review_note" field. It's identical to ReviewNoteEQ.
func ReviewNote(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldReviewNote, v))
}

// AffiliateAction applies equality check predicate on the "affiliate_action" field. It's identical to AffiliateActionEQ.
func AffiliateAction(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldAffiliateAction, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldReviewedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldOrderID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldUserID, v))
}

// RefundIDEQ applies the EQ predicate on the "refund_id" field.
func RefundIDEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldRefundID, v))
}

// RefundIDNEQ applies the NEQ predicate on the "refund_id" field.
func RefundIDNEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldRefundID, v))
}

// RefundIDIn applies the In predicate on the "refund_id" field.
func RefundIDIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldRefundID, vs...))
}

// RefundIDNotIn applies the NotIn predicate on the "refund_id" field.
func RefundIDNotIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldRefundID, vs...))
}

// RefundIDGT applies the GT predicate on the "refund_id" field.
func RefundIDGT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldRefundID, v))
}

// RefundIDGTE applies the GTE predicate on the "refund_id" field.
func RefundIDGTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldRefundID, v))
}

// RefundIDLT applies the LT predicate on the "refund_id" field.
func RefundIDLT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldRefundID, v))
}

// RefundIDLTE applies the LTE predicate on the "refund_id" field.
func RefundIDLTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldRefundID, v))
}

// RefundIDContains applies the Contains predicate on the "refund_id" field.
func RefundIDContains(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContains(FieldRefundID, v))
}

// RefundIDHasPrefix applies the HasPrefix predicate on the "refund_id" field.
func RefundIDHasPrefix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasPrefix(FieldRefundID, v))
}

// RefundIDHasSuffix applies the HasSuffix predicate on the "refund_id" field.
func RefundIDHasSuffix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasSuffix(FieldRefundID, v))
}

// RefundIDIsNil applies the IsNil predicate on the "refund_id" field.
func RefundIDIsNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIsNull(FieldRefundID))
}

// RefundIDNotNil applies the NotNil predicate on the "refund_id" field.
func RefundIDNotNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotNull(FieldRefundID))
}

// RefundIDEqualFold applies the EqualFold predicate on the "refund_id" field.
func RefundIDEqualFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldRefundID, v))
}

// RefundIDContainsFold applies the ContainsFold predicate on the "refund_id" field.
func RefundIDContainsFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldRefundID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldStatus, v))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasSuffix(FieldComment, v))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldComment, v))
}

// ApprovedPrincipalAmountEQ applies the EQ predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountEQ(v float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountNEQ applies the NEQ predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountNEQ(v float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountIn applies the In predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountIn(vs ...float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldApprovedPrincipalAmount, vs...))
}

// ApprovedPrincipalAmountNotIn applies the NotIn predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountNotIn(vs ...float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldApprovedPrincipalAmount, vs...))
}

// ApprovedPrincipalAmountGT applies the GT predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountGT(v float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountGTE applies the GTE predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountGTE(v float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountLT applies the LT predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountLT(v float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountLTE applies the LTE predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountLTE(v float64) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldApprovedPrincipalAmount, v))
}

// ApprovedPrincipalAmountIsNil applies the IsNil predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountIsNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIsNull(FieldApprovedPrincipalAmount))
}

// ApprovedPrincipalAmountNotNil applies the NotNil predicate on the "approved_principal_amount" field.
func ApprovedPrincipalAmountNotNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotNull(FieldApprovedPrincipalAmount))
}

// ReviewerIDEQ applies the EQ predicate on the "reviewer_id" field.
func ReviewerIDEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldReviewerID, v))
}

// ReviewerIDNEQ applies the NEQ predicate on the "reviewer_id" field.
func ReviewerIDNEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldReviewerID, v))
}

// ReviewerIDIn applies the In predicate on the "reviewer_id" field.
func ReviewerIDIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldReviewerID, vs...))
}

// ReviewerIDNotIn applies the NotIn predicate on the "reviewer_id" field.
func ReviewerIDNotIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldReviewerID, vs...))
}

// ReviewerIDGT applies the GT predicate on the "reviewer_id" field.
func ReviewerIDGT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldReviewerID, v))
}

// ReviewerIDGTE applies the GTE predicate on the "reviewer_id" field.
func ReviewerIDGTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldReviewerID, v))
}

// ReviewerIDLT applies the LT predicate on the "reviewer_id" field.
func ReviewerIDLT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldReviewerID, v))
}

// ReviewerIDLTE applies the LTE predicate on the "reviewer_id" field.
func ReviewerIDLTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldReviewerID, v))
}

// ReviewerIDContains applies the Contains predicate on the "reviewer_id" field.
func ReviewerIDContains(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContains(FieldReviewerID, v))
}

// ReviewerIDHasPrefix applies the HasPrefix predicate on the "reviewer_id" field.
func ReviewerIDHasPrefix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasPrefix(FieldReviewerID, v))
}

// ReviewerIDHasSuffix applies the HasSuffix predicate on the "reviewer_id" field.
func ReviewerIDHasSuffix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasSuffix(FieldReviewerID, v))
}

// ReviewerIDIsNil applies the IsNil predicate on the "reviewer_id" field.
func ReviewerIDIsNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIsNull(FieldReviewerID))
}

// ReviewerIDNotNil applies the NotNil predicate on the "reviewer_id" field.
func ReviewerIDNotNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotNull(FieldReviewerID))
}

// ReviewerIDEqualFold applies the EqualFold predicate on the "reviewer_id" field.
func ReviewerIDEqualFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldReviewerID, v))
}

// ReviewerIDContainsFold applies the ContainsFold predicate on the "reviewer_id" field.
func ReviewerIDContainsFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldReviewerID, v))
}

// ReviewNoteEQ applies the EQ predicate on the "review_note" field.
func ReviewNoteEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldReviewNote, v))
}

// ReviewNoteNEQ applies the NEQ predicate on the "review_note" field.
func ReviewNoteNEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldReviewNote, v))
}

// ReviewNoteIn applies the In predicate on the "review_note" field.
func ReviewNoteIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldReviewNote, vs...))
}

// ReviewNoteNotIn applies the NotIn predicate on the "review_note" field.
func ReviewNoteNotIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldReviewNote, vs...))
}

// ReviewNoteGT applies the GT predicate on the "review_note" field.
func ReviewNoteGT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldReviewNote, v))
}

// ReviewNoteGTE applies the GTE predicate on the "review_note" field.
func ReviewNoteGTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldReviewNote, v))
}

// ReviewNoteLT applies the LT predicate on the "review_note" field.
func ReviewNoteLT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldReviewNote, v))
}

// ReviewNoteLTE applies the LTE predicate on the "review_note" field.
func ReviewNoteLTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldReviewNote, v))
}

// ReviewNoteContains applies the Contains predicate on the "review_note" field.
func ReviewNoteContains(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContains(FieldReviewNote, v))
}

// ReviewNoteHasPrefix applies the HasPrefix predicate on the "review_note" field.
func ReviewNoteHasPrefix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasPrefix(FieldReviewNote, v))
}

// ReviewNoteHasSuffix applies the HasSuffix predicate on the "review_note" field.
func ReviewNoteHasSuffix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasSuffix(FieldReviewNote, v))
}

// ReviewNoteEqualFold applies the EqualFold predicate on the "review_note" field.
func ReviewNoteEqualFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldReviewNote, v))
}

// ReviewNoteContainsFold applies the ContainsFold predicate on the "review_note" field.
func ReviewNoteContainsFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldReviewNote, v))
}

// AffiliateActionEQ applies the EQ predicate on the "affiliate_action" field.
func AffiliateActionEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldAffiliateAction, v))
}

// AffiliateActionNEQ applies the NEQ predicate on the "affiliate_action" field.
func AffiliateActionNEQ(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldAffiliateAction, v))
}

// AffiliateActionIn applies the In predicate on the "affiliate_action" field.
func AffiliateActionIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldAffiliateAction, vs...))
}

// AffiliateActionNotIn applies the NotIn predicate on the "affiliate_action" field.
func AffiliateActionNotIn(vs ...string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldAffiliateAction, vs...))
}

// AffiliateActionGT applies the GT predicate on the "affiliate_action" field.
func AffiliateActionGT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldAffiliateAction, v))
}

// AffiliateActionGTE applies the GTE predicate on the "affiliate_action" field.
func AffiliateActionGTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldAffiliateAction, v))
}

// AffiliateActionLT applies the LT predicate on the "affiliate_action" field.
func AffiliateActionLT(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldAffiliateAction, v))
}

// AffiliateActionLTE applies the LTE predicate on the "affiliate_action" field.
func AffiliateActionLTE(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldAffiliateAction, v))
}

// AffiliateActionContains applies the Contains predicate on the "affiliate_action" field.
func AffiliateActionContains(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContains(FieldAffiliateAction, v))
}

// AffiliateActionHasPrefix applies the HasPrefix predicate on the "affiliate_action" field.
func AffiliateActionHasPrefix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasPrefix(FieldAffiliateAction, v))
}

// AffiliateActionHasSuffix applies the HasSuffix predicate on the "affiliate_action" field.
func AffiliateActionHasSuffix(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldHasSuffix(FieldAffiliateAction, v))
}

// AffiliateActionEqualFold applies the EqualFold predicate on the "affiliate_action" field.
func AffiliateActionEqualFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEqualFold(FieldAffiliateAction, v))
}

// AffiliateActionContainsFold applies the ContainsFold predicate on the "affiliate_action" field.
func AffiliateActionContainsFold(v string) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldContainsFold(FieldAffiliateAction, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotNull(FieldReviewedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RefundTicket {
	return predicate.RefundTicket(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RefundTicket) predicate.RefundTicket {
	return predicate.RefundTicket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RefundTicket) predicate.RefundTicket {
	return predicate.RefundTicket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RefundTicket) predicate.RefundTicket {
	return predicate.RefundTicket(sql.NotPredicates(p))
}
