// Code generated by ent, DO NOT EDIT.

package supportticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/AsukaCC/EasySub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorRole applies equality check predicate on the "author_role" field. It's identical to AuthorRoleEQ.
func AuthorRole(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorRole, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldKind, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldBody, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldEventType, v))
}

// EventData applies equality check predicate on the "event_data" field. It's identical to EventDataEQ.
func EventData(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldEventData, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// TicketIDGT applies the GT predicate on the "ticket_id" field.
func TicketIDGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldTicketID, v))
}

// TicketIDGTE applies the GTE predicate on the "ticket_id" field.
func TicketIDGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldTicketID, v))
}

// TicketIDLT applies the LT predicate on the "ticket_id" field.
func TicketIDLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldTicketID, v))
}

// TicketIDLTE applies the LTE predicate on the "ticket_id" field.
func TicketIDLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldTicketID, v))
}

// TicketIDContains applies the Contains predicate on the "ticket_id" field.
func TicketIDContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldTicketID, v))
}

// TicketIDHasPrefix applies the HasPrefix predicate on the "ticket_id" field.
func TicketIDHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldTicketID, v))
}

// TicketIDHasSuffix applies the HasSuffix predicate on the "ticket_id" field.
func TicketIDHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldTicketID, v))
}

// TicketIDEqualFold applies the EqualFold predicate on the "ticket_id" field.
func TicketIDEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldTicketID, v))
}

// TicketIDContainsFold applies the ContainsFold predicate on the "ticket_id" field.
func TicketIDContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldTicketID, v))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDGT applies the GT predicate on the "author_id" field.
func AuthorIDGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldAuthorID, v))
}

// AuthorIDGTE applies the GTE predicate on the "author_id" field.
func AuthorIDGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldAuthorID, v))
}

// AuthorIDLT applies the LT predicate on the "author_id" field.
func AuthorIDLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldAuthorID, v))
}

// AuthorIDLTE applies the LTE predicate on the "author_id" field.
func AuthorIDLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldAuthorID, v))
}

// AuthorIDContains applies the Contains predicate on the "author_id" field.
func AuthorIDContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldAuthorID, v))
}

// AuthorIDHasPrefix applies the HasPrefix predicate on the "author_id" field.
func AuthorIDHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldAuthorID, v))
}

// AuthorIDHasSuffix applies the HasSuffix predicate on the "author_id" field.
func AuthorIDHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldAuthorID, v))
}

// AuthorIDIsNil applies the IsNil predicate on the "author_id" field.
func AuthorIDIsNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIsNull(FieldAuthorID))
}

// AuthorIDNotNil applies the NotNil predicate on the "author_id" field.
func AuthorIDNotNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotNull(FieldAuthorID))
}

// AuthorIDEqualFold applies the EqualFold predicate on the "author_id" field.
func AuthorIDEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldAuthorID, v))
}

// AuthorIDContainsFold applies the ContainsFold predicate on the "author_id" field.
func AuthorIDContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldAuthorID, v))
}

// AuthorRoleEQ applies the EQ predicate on the "author_role" field.
func AuthorRoleEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorRole, v))
}

// AuthorRoleNEQ applies the NEQ predicate on the "author_role" field.
func AuthorRoleNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorRole, v))
}

// AuthorRoleIn applies the In predicate on the "author_role" field.
func AuthorRoleIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorRole, vs...))
}

// AuthorRoleNotIn applies the NotIn predicate on the "author_role" field.
func AuthorRoleNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorRole, vs...))
}

// AuthorRoleGT applies the GT predicate on the "author_role" field.
func AuthorRoleGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldAuthorRole, v))
}

// AuthorRoleGTE applies the GTE predicate on the "author_role" field.
func AuthorRoleGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldAuthorRole, v))
}

// AuthorRoleLT applies the LT predicate on the "author_role" field.
func AuthorRoleLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldAuthorRole, v))
}

// AuthorRoleLTE applies the LTE predicate on the "author_role" field.
func AuthorRoleLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldAuthorRole, v))
}

// AuthorRoleContains applies the Contains predicate on the "author_role" field.
func AuthorRoleContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldAuthorRole, v))
}

// AuthorRoleHasPrefix applies the HasPrefix predicate on the "author_role" field.
func AuthorRoleHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldAuthorRole, v))
}

// AuthorRoleHasSuffix applies the HasSuffix predicate on the "author_role" field.
func AuthorRoleHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldAuthorRole, v))
}

// AuthorRoleEqualFold applies the EqualFold predicate on the "author_role" field.
func AuthorRoleEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldAuthorRole, v))
}

// AuthorRoleContainsFold applies the ContainsFold predicate on the "author_role" field.
func AuthorRoleContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldAuthorRole, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldKind, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldBody, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldEventType, v))
}

// EventDataEQ applies the EQ predicate on the "event_data" field.
func EventDataEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldEventData, v))
}

// EventDataNEQ applies the NEQ predicate on the "event_data" field.
func EventDataNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldEventData, v))
}

// EventDataIn applies the In predicate on the "event_data" field.
func EventDataIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldEventData, vs...))
}

// EventDataNotIn applies the NotIn predicate on the "event_data" field.
func EventDataNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldEventData, vs...))
}

// EventDataGT applies the GT predicate on the "event_data" field.
func EventDataGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldEventData, v))
}

// EventDataGTE applies the GTE predicate on the "event_data" field.
func EventDataGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldEventData, v))
}

// EventDataLT applies the LT predicate on the "event_data" field.
func EventDataLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldEventData, v))
}

// EventDataLTE applies the LTE predicate on the "event_data" field.
func EventDataLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldEventData, v))
}

// EventDataContains applies the Contains predicate on the "event_data" field.
func EventDataContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldEventData, v))
}

// EventDataHasPrefix applies the HasPrefix predicate on the "event_data" field.
func EventDataHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldEventData, v))
}

// EventDataHasSuffix applies the HasSuffix predicate on the "event_data" field.
func EventDataHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldEventData, v))
}

// EventDataEqualFold applies the EqualFold predicate on the "event_data" field.
func EventDataEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldEventData, v))
}

// EventDataContainsFold applies the ContainsFold predicate on the "event_data" field.
func EventDataContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldEventData, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.NotPredicates(p))
}
